import { useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Plus, Search } from "lucide-react";
import {
  activeQualificationConfiguration,
  caseOverview,
  deriveQualificationStatus,
  priorityEligibilityBlockers,
} from "../application/selectors";
import type { Command, CommandResult, DemoState } from "../application";
import {
  createId,
  type ChallengeId,
  type CompletionRequirementId,
  type InitiativeId,
  type RoleAssignmentId,
} from "../domain";
import { qualificationAreaLabels } from "../application/selectors/qualificationSelectors";

const stepLabels = {
  UTKAST: "Utkast",
  REGISTRERAD: "Registrerad utmaning",
  BEREDNING: "Under beredning",
  PRIORITERINGSBAR: "Prioriteringsbar",
} as const;
const process = ["Utmaning", "Businesscase", "Kvalificering", "Prioritering", "Effektåtagande", "Startbeslut", "Effektuppföljning"];
const emptyCase = { title: "", problemStatement: "", currentState: "", strategicHandlingReason: "", strategicRelevance: "", purpose: "", desiredState: "", scope: "", alternatives: "", doNothingConsequence: "", evidence: "", assumptions: "", uncertainty: "", timeHorizon: "", knownPrerequisites: "", knownRisks: "" };

export interface CaseNavigationContext { activeId?: ChallengeId; query: string; stepFilter: string; }

export function CaseWorkspace({ state, dispatch, openPortfolio, context, setContext, feedback }: {
  state: DemoState;
  dispatch: (command: Command) => CommandResult;
  openPortfolio: (id: InitiativeId) => void;
  context: CaseNavigationContext;
  setContext: (next: CaseNavigationContext) => void;
  feedback: string;
}) {
  const [showNew, setShowNew] = useState(false);
  const [form, setForm] = useState(emptyCase);
  const [requirement, setRequirement] = useState({ missing: "", reason: "", responsible: "", verifier: "", deadline: "" });
  const [answers, setAnswers] = useState<Record<string, { summary: string; evidence: string }>>({});
  const [initiativeDraft, setInitiativeDraft] = useState({ title: "", purpose: "", desiredEndState: "", scope: "" });
  const [potential, setPotential] = useState({ measure: "", lower: "", expected: "", upper: "", unit: "", evidence: "", assumption: "", horizon: "12 månader" });
  const items = useMemo(() => caseOverview(state), [state]);
  const active = context.activeId ? items.find((item) => item.challengeId === context.activeId) : undefined;
  const challenge = active ? state.entities.challenges[active.challengeId] : undefined;
  const initiative = active?.initiativeId ? state.entities.initiatives[active.initiativeId] : undefined;
  const requirements = challenge ? Object.values(state.entities.completionRequirements).filter((item) => item.challengeId === challenge.id || item.initiativeId === initiative?.id) : [];
  const config = activeQualificationConfiguration(state);
  const initiatorActor = Object.values(state.entities.roleAssignments).find((assignment) => state.entities.roleDefinitions[assignment.roleDefinitionId]?.roleKind === "INITIATOR")!;
  const specialistActor = Object.values(state.entities.roleAssignments).find((assignment) => state.entities.roleDefinitions[assignment.roleDefinitionId]?.roleKind === "SPECIALIST")!;
  const decisionActor = Object.values(state.entities.roleAssignments).find((assignment) => state.entities.roleDefinitions[assignment.roleDefinitionId]?.roleKind === "DECISION_MAKER")!;
  const send = (command: Record<string, unknown>, actor: RoleAssignmentId = initiatorActor.id) => dispatch({ ...command, commandId: createId("Command", `case-${Date.now()}-${Math.random().toString(36).slice(2)}`), actorRoleAssignmentId: actor, issuedAt: new Date().toISOString() } as Command);
  const openCase = (id: ChallengeId) => {
    const item = state.entities.challenges[id];
    setForm({ ...emptyCase, title: item.title, problemStatement: item.problemStatement, currentState: item.currentState, strategicHandlingReason: item.strategicHandlingReason, strategicRelevance: item.strategicRelevance, ...(item.businessCase ?? {}) });
    setContext({ ...context, activeId: id });
  };

  if (active && challenge) {
    const businessComplete = Boolean(challenge.businessCase?.purpose && challenge.businessCase.desiredState && challenge.businessCase.scope && challenge.businessCase.alternatives && challenge.businessCase.doNothingConsequence);
    const qualification = initiative ? deriveQualificationStatus(state, initiative.id) : undefined;
    const stepIndex = challenge.nominationStatus === "DRAFT" ? 0 : !businessComplete ? 1 : qualification?.status !== "QUALIFIED" ? 2 : 3;
    const saveMaterial = (nominationStatus = challenge.nominationStatus) => send({ commandType: "UPDATE_STRATEGIC_CHALLENGE", targetId: challenge.id, payload: { title: form.title, problemStatement: form.problemStatement, currentState: form.currentState, strategicHandlingReason: form.strategicHandlingReason, strategicRelevance: form.strategicRelevance, nominationStatus, businessCase: { templateId: "DEMO-CASE-V1", purpose: form.purpose, desiredState: form.desiredState, scope: form.scope, alternatives: form.alternatives, doNothingConsequence: form.doNothingConsequence, evidence: form.evidence, assumptions: form.assumptions, uncertainty: form.uncertainty, timeHorizon: form.timeHorizon, knownPrerequisites: form.knownPrerequisites, knownRisks: form.knownRisks } } });
    return <section className="case-workspace" aria-label="Ärendevy">
      <button className="back-link" onClick={() => setContext({ ...context, activeId: undefined })}><ArrowLeft size={16}/> Till ärendeöversikten (filter bevaras)</button>
      <div className="case-detail-head"><div><p className="eyebrow">{active.caseNumber} · {stepLabels[active.step]}</p><h1>{active.title}</h1><p>{challenge.problemStatement || "Problemformulering saknas."}</p></div><span className="demo-role">Fiktiv demosession<small>Roll används per handling – ingen verklig autentisering</small></span></div>
      <ol className="process-indicator">{process.map((label, index) => <li className={index < stepIndex ? "done" : index === stepIndex ? "current" : "upcoming"} key={label}>{index < stepIndex && <Check size={14}/>}<span>{label}</span>{index >= 4 && <small>Kommande – ej implementerat</small>}</li>)}</ol>
      <p role="status" className="inline-feedback">{feedback}</p>
      <div className="case-columns">
        <article className="card"><p className="eyebrow">REDIGERBART GEMENSAMT UNDERLAG</p><h2>Utmaning och businesscase</h2><p className="template-note">Demonstrationsmall v1 · konfigurerbar struktur · inte verifierad som PPS-komplett</p>
          <form className="material-form" onSubmit={(event) => { event.preventDefault(); saveMaterial(); }}>
            {[ ["title","Titel"], ["problemStatement","Problem och behov"], ["currentState","Nuläge"], ["strategicHandlingReason","Varför strategisk hantering?"], ["strategicRelevance","Strategisk relevans"], ["purpose","Syfte"], ["desiredState","Önskat förändrat läge"], ["scope","Avgränsning"], ["alternatives","Alternativ"], ["doNothingConsequence","Om vi avstår"], ["evidence","Evidens"], ["assumptions","Antaganden"], ["uncertainty","Osäkerhet"], ["timeHorizon","Tidshorisont"], ["knownPrerequisites","Kända förutsättningar"], ["knownRisks","Kända risker"] ].map(([key,label]) => <label key={key}>{label}<textarea value={form[key as keyof typeof form]} onChange={(event) => setForm({ ...form, [key]: event.target.value })}/></label>)}
            <button>Spara underlag</button>
          </form>
          {challenge.nominationStatus === "DRAFT" && <button onClick={() => saveMaterial("NOMINATED")}>Skicka utmaning till beredning</button>}
          {challenge.nominationStatus === "NOMINATED" && !initiative && <form onSubmit={(event) => { event.preventDefault(); const result = send({ commandType: "CREATE_INITIATIVE_FROM_CHALLENGE", targetId: createId("Initiative", `preparation-${challenge.id}`), payload: { challengeId: challenge.id, ...initiativeDraft, initiativeKind: "VALUE_CREATING" } }); if (result.success) setInitiativeDraft({ title: "", purpose: "", desiredEndState: "", scope: "" }); }}><h3>Skapa länkat beredningsinitiativ</h3>{Object.entries(initiativeDraft).map(([key,value]) => <label key={key}>{({title:"Titel",purpose:"Syfte",desiredEndState:"Önskat läge",scope:"Avgränsning"} as Record<string,string>)[key]}<input required value={value} onChange={(event)=>setInitiativeDraft({...initiativeDraft,[key]:event.target.value})}/></label>)}<button>Registrera initiativ för beredning</button><small>Registrering är inte ett startbeslut.</small></form>}
          {initiative && <><p className="linked-note">Potential, förutsättningar och kostnader hämtas från länkade domänobjekt och kopieras inte hit.</p><button onClick={() => openPortfolio(initiative.id)}>Öppna potential, beroenden och kostnader <ChevronRight size={16}/></button></>}
          <details className="trace"><summary>Fördjupad spårbarhet</summary><code>{challenge.id}</code>{initiative && <code>{initiative.id}</code>}</details>
        </article>
        <aside className="card"><p className="eyebrow">HINDER OCH NÄSTA STEG</p><h2>{active.nextAction}</h2><p><b>Hinder:</b> {active.obstacle}</p><p><b>Ansvarig:</b> {active.responsible}</p><p><b>Datum:</b> {active.dueDate ?? "Datum saknas"} {active.overdue && <strong className="overdue">Försenad</strong>}</p>
          {requirements.map((item) => <CompletionCard key={item.id} itemId={item.id} state={state} send={send}/>) }
          <form onSubmit={(event) => { event.preventDefault(); send({ commandType:"CREATE_COMPLETION_REQUIREMENT", targetId:createId("CompletionRequirement", `ui-${Date.now()}`), payload:{ challengeId:challenge.id, initiativeId:initiative?.id, missingItem:requirement.missing, reasonRequired:requirement.reason, blocks:["QUALIFICATION"], responsibleRoleAssignmentId: requirement.responsible || undefined, verifierRoleAssignmentId: requirement.verifier || undefined, deadline: requirement.deadline || undefined } }); }}><h3>Lägg till kompletteringskrav</h3><input required aria-label="Vad saknas" placeholder="Vad saknas?" value={requirement.missing} onChange={(event)=>setRequirement({...requirement,missing:event.target.value})}/><input required aria-label="Varför behövs uppgiften" placeholder="Varför behövs uppgiften?" value={requirement.reason} onChange={(event)=>setRequirement({...requirement,reason:event.target.value})}/><RoleSelect label="Den som kompletterar" value={requirement.responsible} state={state} onChange={(responsible)=>setRequirement({...requirement,responsible})}/><RoleSelect label="Den som verifierar" value={requirement.verifier} state={state} onChange={(verifier)=>setRequirement({...requirement,verifier})}/><input aria-label="Förfallodatum" type="date" value={requirement.deadline} onChange={(event)=>setRequirement({...requirement,deadline:event.target.value})}/><button>Spara krav</button></form>
        </aside>
      </div>
      {initiative && config && <section className="card qualification-editor"><p className="eyebrow">BEDÖMD EFFEKTPOTENTIAL</p><h2>Potential före prioritering</h2><p>Bedömningen är icke bindande och är inte ett lokalt effektåtagande.</p><form className="potential-form" onSubmit={(event)=>{event.preventDefault();send({commandType:"RECORD_EFFECT_POTENTIAL",targetId:createId("EffectPotential",`case-${Date.now()}`),payload:{seriesId:`CASE-${initiative.id}-POTENTIAL`,initiativeId:initiative.id,recipientScenario:"Preliminära effektmottagare",category:"OTHER_BUSINESS_EFFECT",effectMeasureCode:potential.measure,unit:potential.unit,lowerBound:Number(potential.lower),expectedValue:Number(potential.expected),upperBound:Number(potential.upper),evidenceRefs:[potential.evidence],assumptions:[potential.assumption],uncertainty:"MEDIUM",realizationWindow:potential.horizon,earliestPossibleEffectDate:new Date().toISOString().slice(0,10),fullPotentialDate:new Date(Date.now()+365*86400000).toISOString().slice(0,10),scope:"FEDERATED_SCENARIO",assessmentVersion:1}},specialistActor.id)}}>{Object.entries(potential).map(([key,value])=><label key={key}>{({measure:"Effektmått",lower:"Låg",expected:"Förväntad",upper:"Hög",unit:"Enhet",evidence:"Evidens",assumption:"Antagande",horizon:"Tidshorisont"} as Record<string,string>)[key]}<input required value={value} type={["lower","expected","upper"].includes(key)?"number":"text"} onChange={(event)=>setPotential({...potential,[key]:event.target.value})}/></label>)}<button>Spara bedömd potential</button></form>
        <p className="eyebrow">INDIVIDUELLA BEDÖMNINGAR</p><h2>Kvalificering</h2><p>Varje punkt bedöms och sparas separat. Ett svar på en komplettering godkänner inga punkter.</p>{config.criteria.map((criterion) => { const current=Object.values(state.entities.qualificationAssessments).find((item)=>item.initiativeId===initiative.id&&item.criterionCode===criterion.criterionCode); const draft=answers[criterion.criterionCode] ?? {summary:current?.summary??"",evidence:current?.evidenceRefs[0]??""}; return <div className="criterion" key={criterion.criterionCode}><div><b>{criterion.name}</b><small>{qualificationAreaLabels[criterion.qualificationArea]} · {criterion.helpText}</small></div><input aria-label={`Bedömning ${criterion.name}`} placeholder="Bedömning" value={draft.summary} onChange={(event)=>setAnswers({...answers,[criterion.criterionCode]:{...draft,summary:event.target.value}})}/><input aria-label={`Underlag ${criterion.name}`} placeholder="Underlagsreferens" value={draft.evidence} onChange={(event)=>setAnswers({...answers,[criterion.criterionCode]:{...draft,evidence:event.target.value}})}/><button onClick={()=>send({commandType:"UPSERT_QUALIFICATION_ASSESSMENT",targetId:current?.id??createId("QualificationAssessment",`${initiative.id}-${criterion.criterionCode.toLowerCase().replaceAll("_","-")}`),payload:{initiativeId:initiative.id,qualificationArea:criterion.qualificationArea,criterionCode:criterion.criterionCode,summary:draft.summary,status:"SATISFIED",mandatory:criterion.mandatory,requiresVerification:criterion.requiresVerification,evidenceRefs:[draft.evidence],assumptions:[],assessedAgainstConfigurationVersion:config.id}}, initiatorActor.id)}>Spara punkt</button>{current?.requiresVerification&&!current.verifiedAt&&<button onClick={()=>send({commandType:"VERIFY_QUALIFICATION_ASSESSMENT",targetId:current.id},specialistActor.id)}>Specialistverifiera</button>}</div>})}
        <button onClick={()=>{ const profile=Object.values(state.entities.steeringProfileVersions).find((item)=>item.status==="ACTIVE")!; const blockers=priorityEligibilityBlockers(state,initiative.id,profile); const scores=Object.fromEntries(profile.criteria.map((criterion)=>[criterion.code,{score:3,evidenceRefs:[`Ärendeunderlag ${challenge.id}`],uncertainty:"MEDIUM" as const}])); send({commandType:"CALCULATE_PRIORITY_ASSESSMENT",targetId:createId("PriorityAssessment",`case-${Date.now()}`),payload:{initiativeId:initiative.id,steeringProfileVersionId:profile.id,scores}},decisionActor.id); void blockers; }}>Pröva skapa prioriteringsunderlag</button>
      </section>}
    </section>;
  }

  const filtered = items.filter((item) => (context.stepFilter === "ALL" || item.step === context.stepFilter) && `${item.caseNumber} ${item.title} ${item.area}`.toLocaleLowerCase("sv").includes(context.query.toLocaleLowerCase("sv")));
  return <section className="case-workspace" aria-label="Ärendeöversikt"><div className="overview-head"><div><p className="eyebrow">STRATEGISKA ÄRENDEN</p><h1>Vad behöver ledningens uppmärksamhet?</h1><p>Härledda processteg, faktiska hinder och ägare till nästa handling. Arbetslistan är inte en prioriteringsranking.</p></div><button onClick={()=>setShowNew(!showNew)}><Plus size={17}/> Registrera utmaning</button></div>
    <p role="status" className="inline-feedback">{feedback}</p>
    {showNew && <form className="new-case" onSubmit={(event)=>{event.preventDefault();const id=createId("Challenge",`user-${Date.now()}`);const result=send({commandType:"CREATE_STRATEGIC_CHALLENGE",targetId:id,payload:{title:form.title,problemStatement:form.problemStatement,currentState:form.currentState,source:"Registrerad i demosessionen",strategicRelevance:form.strategicRelevance,strategicHandlingReason:form.strategicHandlingReason,nominationStatus:"DRAFT"}});if(result.success){setShowNew(false);setContext({...context,activeId:id});}}}><h2>Nytt utkast</h2><p>Tomma uppgifter får sparas och kompletteras senare.</p><label>Titel<input value={form.title} onChange={(event)=>setForm({...form,title:event.target.value})}/></label><label>Problem<textarea value={form.problemStatement} onChange={(event)=>setForm({...form,problemStatement:event.target.value})}/></label><button>Spara utkast i demosessionen</button></form>}
    <div className="case-toolbar"><label><Search size={16}/><input aria-label="Sök ärenden" placeholder="Sök nummer, titel eller område" value={context.query} onChange={(event)=>setContext({...context,query:event.target.value})}/></label><select aria-label="Filtrera processteg" value={context.stepFilter} onChange={(event)=>setContext({...context,stepFilter:event.target.value})}><option value="ALL">Alla processteg</option>{Object.entries(stepLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><span>Sorterad: äldsta först · {filtered.length} av {items.length}</span></div>
    <div className="case-table" role="table"><div className="case-row case-header" role="row"><span>Ärende</span><span>Steg och hinder</span><span>Nästa åtgärd</span><span>Ansvar och datum</span></div>{filtered.map((item)=><button className="case-row" role="row" key={item.challengeId} onClick={()=>openCase(item.challengeId)}><span><b>{item.caseNumber}</b><strong>{item.title}</strong><small>{item.area}</small></span><span><i>{stepLabels[item.step]}</i><small>{item.obstacle}</small></span><span><strong>{item.nextAction}</strong>{!item.comparable&&<small>Kan inte jämföras: {item.comparisonReason}</small>}</span><span><b>{item.responsible}</b><small>{item.dueDate??"Datum saknas"} {item.overdue&&<em>Försenad</em>}</small></span></button>)}</div><p className="session-note">Demoklocka: aktuell systemdag {new Date().toLocaleDateString("sv-SE")}. Ändringar finns bara i demosessionen.</p></section>;
}

function RoleSelect({label,value,state,onChange}:{label:string;value:string;state:DemoState;onChange:(value:string)=>void}) { return <label>{label}<select value={value} onChange={(event)=>onChange(event.target.value)}><option value="">Ansvarig saknas</option>{Object.values(state.entities.roleAssignments).map((assignment)=><option key={assignment.id} value={assignment.id}>{state.entities.people[assignment.personId].displayName} · {state.entities.roleDefinitions[assignment.roleDefinitionId].name}</option>)}</select></label> }
function CompletionCard({itemId,state,send}:{itemId:CompletionRequirementId;state:DemoState;send:(command:Record<string,unknown>,actor?:RoleAssignmentId)=>CommandResult}) { const item=state.entities.completionRequirements[itemId]; const [answer,setAnswer]=useState(""); const [assignment,setAssignment]=useState({responsible:item.responsibleRoleAssignmentId??"",verifier:item.verifierRoleAssignmentId??"",deadline:item.deadline??""}); const specialist=Object.values(state.entities.roleAssignments).find((assignment)=>state.entities.roleDefinitions[assignment.roleDefinitionId]?.roleKind==="SPECIALIST")!; const role=(id?:RoleAssignmentId)=>id?`${state.entities.people[state.entities.roleAssignments[id].personId].displayName} · ${state.entities.roleDefinitions[state.entities.roleAssignments[id].roleDefinitionId].name}`:"Saknas"; return <div className="requirement"><b>{item.missingItem}</b><span>Varför: {item.reasonRequired}</span><span>Blockerar: {item.blocks.join(", ")}</span><span>Kompletterar: {role(item.responsibleRoleAssignmentId)}</span><span>Verifierar: {role(item.verifierRoleAssignmentId)}</span><span>Datum: {item.deadline??"Saknas"} · Status: {item.status}</span><span>Svar: {item.resolutionSummary||"Dokumenterat svar saknas"}</span>{(!item.responsibleRoleAssignmentId||!item.deadline)&&<div className="requirement-assignment"><RoleSelect label="Tilldela kompletterare" value={assignment.responsible} state={state} onChange={(responsible)=>setAssignment({...assignment,responsible})}/><RoleSelect label="Tilldela verifierare" value={assignment.verifier} state={state} onChange={(verifier)=>setAssignment({...assignment,verifier})}/><input aria-label="Sätt förfallodatum" type="date" value={assignment.deadline} onChange={(event)=>setAssignment({...assignment,deadline:event.target.value})}/><button disabled={!assignment.responsible||!assignment.deadline} onClick={()=>send({commandType:"ASSIGN_COMPLETION_RESPONSIBILITY",targetId:item.id,payload:{responsibleRoleAssignmentId:assignment.responsible,verifierRoleAssignmentId:assignment.verifier||undefined,deadline:assignment.deadline}})}>Tilldela krav</button></div>}{!["VERIFIED","NOT_APPLICABLE"].includes(item.status)&&<><input aria-label={`Svar ${item.missingItem}`} value={answer} onChange={(event)=>setAnswer(event.target.value)} placeholder="Dokumenterat svar"/>{item.status!=="SUBMITTED"?<button onClick={()=>send({commandType:"SUBMIT_COMPLETION_REQUIREMENT",targetId:item.id,payload:{submittedEvidenceRefs:[`DEMO-SVAR-${item.id}`],resolutionSummary:answer}},item.responsibleRoleAssignmentId)}>Skicka svar</button>:<button onClick={()=>send({commandType:"VERIFY_COMPLETION_REQUIREMENT",targetId:item.id,payload:{resolutionSummary:answer||item.resolutionSummary||"Verifierat svar"}},item.verifierRoleAssignmentId??specialist.id)}>Verifiera svar</button>}</>}</div> }
