import type { StrategicChallenge } from "../domain/challenge";
import { businessCaseFields, challengeFields, requiredBusinessCaseKeys, requiredChallengeKeys } from "../domain/caseDocumentRequirements";
import { DocumentPanel } from "./DocumentPanel";

export function CaseDocumentEditor({kind,challenge,values,onChange,onSave,onNominate,onRegister,canRegister,onNext}:{kind:"material"|"businesscase";challenge:StrategicChallenge;values:Record<string,string>;onChange:(patch:Record<string,string>)=>void;onSave:()=>void;onNominate:()=>void;onRegister:()=>void;canRegister:boolean;onNext:()=>void}) {
 const bc=kind==="businesscase",labels=bc?businessCaseFields:challengeFields,required:readonly string[]=bc?requiredBusinessCaseKeys:requiredChallengeKeys;
 const fields=Object.entries(labels).map(([key,label])=>({key,label,required:required.includes(key)}));
 const saved:Record<string,string>=bc?{...challenge.businessCase}:{title:challenge.title,problemStatement:challenge.problemStatement,currentState:challenge.currentState,strategicHandlingReason:challenge.strategicHandlingReason,strategicRelevance:challenge.strategicRelevance};
 return <article className="card case-document"><h2>{bc?"Businesscase":"Utmaning"}</h2><p>{bc?"Ett separat underlag för att bedöma om och hur utmaningen bör gå vidare. Bedömd effektpotential och nyttokalkyl hör till detta steg; detta är inget bindande effektåtagande.":"Grunduppgifterna beskriver behovet. Här behöver du inte fylla i en kalkyl eller besluta om effektmål."}</p><details className="document-support"><summary>Mallar, bilagor och metodstöd</summary><p className="template-note">Demonstrationsmall v2. Verksamheten beskriver behov och alternativ; initiativets beredare samordnar underlaget. Ekonomi och specialister kompletterar kalkyl och bedömningar. Gemensam PPS-anpassning återstår att fastställa.</p>
 {bc&&<p><a href="./mallar/Nyttokalkyl.xlsx" download>Ladda ner nyttokalkyl i Excel</a> · Kalkylen är ett separat underlag till businesscase och bedömd effektpotential. Ladda upp den som bilaga vid dokumentet.</p>}
 <DocumentPanel kind={bc?"businesscase":"utmaning"} caseId={challenge.id} title={bc?"Businesscase":"Utmaning"} purpose={bc?"Jämför handlingsalternativ och samla underlag inför kvalificering och prioritering.":"Beskriv problem, nuläge och skälet till strategisk hantering."} fields={fields} values={Object.fromEntries(fields.map(f=>[f.key,values[f.key]??""]))} onImport={onChange}/></details>
 <details className="saved-document"><summary>Visa sparade grunduppgifter</summary><dl className="material-summary">{fields.filter(f=>f.required).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{saved[f.key]||"Behöver kompletteras"}</dd></div>)}</dl></details>
 {bc&&challenge.nominationStatus!=="NOMINATED"?<p className="gate blocked">Färdigställ och registrera utmaningen först. Businesscase är nästa separata dokument.</p>:<details data-step-work={kind} className="point-detail" open={required.some(k=>!saved[k]?.trim())?true:undefined}><summary>Fyll i eller komplettera {bc?"businesscase":"utmaningen"} online</summary><form className="material-form" onSubmit={e=>{e.preventDefault();onSave();}}><p>* Krävs inför nästa steg. Delvis ifyllda utkast kan sparas.</p>{fields.filter(f=>f.required).map(f=><label key={f.key}>{f.label} *<textarea value={values[f.key]??""} onChange={e=>onChange({[f.key]:e.target.value})}/></label>)}<details className="material-group"><summary>Fördjupning vid behov</summary>{fields.filter(f=>!f.required).map(f=><label key={f.key}>{f.label}<textarea value={values[f.key]??""} onChange={e=>onChange({[f.key]:e.target.value})}/></label>)}</details><button>Spara {bc?"businesscase":"utmaning"}</button></form></details>}
 {!bc&&(challenge.nominationStatus==="DRAFT"?<button onClick={onNominate}>Registrera utmaning för fortsatt beredning</button>:<button onClick={onNext}>Fortsätt till businesscase</button>)}
 {bc&&challenge.nominationStatus==="NOMINATED"&&!challenge.relatedInitiativeIds.length&&<div className="preparation-handoff"><p>När dokumentet är färdigställt kan initiativet registreras för fortsatt beredning och nyttokalkyl. Titel, syfte, önskat läge och avgränsning följer med från sparade uppgifter.</p><button disabled={!canRegister} onClick={onRegister}>Registrera initiativ för beredning</button><p className="muted">Registrering är inte prioritering eller startbeslut.</p></div>}
 </article>;
}
