import { PortfolioEffects } from "./PortfolioEffects";
import type { Command,CommandResult } from "../application";
import type { FlowStepKey } from "../application/selectors/flowSelectors";
import { latestDecision } from "../application/selectors/transformationSelectors";
import { ArrowUpRight, ArrowRight, Activity, Network, TrendingUp } from "lucide-react";
import type { DemoState } from "../application";
import type { InitiativeId, RoleAssignmentId } from "../domain";
import { cockpitCases, initiativeDependencies } from "../application/selectors/cockpitSelectors";
import { roleName } from "./transformationHelpers";
import { DataProvenance } from "./DataProvenance";

export function CockpitOverview({state,day,ids,open,openCases,area="Alla"}:{state:DemoState;day:string;ids:InitiativeId[];open:(id:InitiativeId,section?:FlowStepKey)=>void;openCases:()=>void;dispatch?:(command:Command)=>CommandResult;area?:string}) {
  const cases=cockpitCases(state,day).filter(c=>c.initiativeId&&ids.includes(c.initiativeId));
  const candidates=cases.filter(c=>!latestDecision(state,c.initiativeId!));
  const ranked=candidates.filter(c=>c.rankable);
  const dependencies=initiativeDependencies(state,ids);
  const events=[...state.audit].reverse().slice(0,4);
  const labels:Record<string,string>={SAVE_EFFECT_COMMITMENT:"Åtagandeutkast sparat",ACCEPT_EFFECT_COMMITMENT:"Effektägaren har accepterat",DECIDE_TRANSFORMATION:"Mänskligt beslut dokumenterat",VERIFY_EFFECT_MEASUREMENT:"Mätpunkt verifierad",CONFIRM_BUSINESS_CHANGE:"Verksamhetsförändring bekräftad",CALCULATE_PRIORITY_ASSESSMENT:"Prioriteringsunderlag beräknat",RECORD_EFFECT_POTENTIAL:"Ny effektpotential dokumenterad",UPDATE_STRATEGIC_CHALLENGE:"Utmaningens underlag uppdaterat",RECORD_EFFECT_MEASUREMENT:"Mätpunkt rapporterad"};
  return <div className="cockpit-overview">
    <PortfolioEffects state={state} ids={ids} area={area} day={day} open={open}/>
    <div className="cockpit-priority"><section className="cockpit-panel"><div className="panel-title"><div><p className="eyebrow">PRIORITERING PÅ GEMENSAM GRUND</p><h2>Det här ligger högst</h2></div><TrendingUp size={24}/></div><p>Senaste giltiga underlag i aktiv styrprofil. Poängen väger samman effekt med övriga kriterier.</p><ol className="priority-ladder">{ranked.slice(0,4).map((c,index)=><li key={c.challengeId}><button onClick={()=>open(c.initiativeId!)}><span className="rank-index">{index+1}</span><span className="rank-copy"><b>{c.title}</b><span className="score-track"><span style={{width:`${c.priorityScore}%`}}/></span><small>{c.assessment?.status==="CALCULATED"?"Beräknat · mänsklig granskning återstår":"Mänskligt granskat underlag"} · {dependencies.some(d=>d.initiativeId===c.initiativeId&&!d.available)?"beroende återstår":"se startkrav i ärendet"}</small></span><span className="rank-score">{c.priorityScore}<small>/100</small><ArrowUpRight size={19}/></span></button></li>)}</ol>{!ranked.length&&<p>Inget giltigt prioriteringsunderlag finns i urvalet ännu.</p>}<button className="outline-link" onClick={openCases}>Öppna hela ärendelistan <ArrowRight size={18}/></button><p className="chart-caption">{candidates.length-ranked.length} ärenden i urvalet saknar aktuell prioriteringsplacering. Hög prioritet ger inte tillstånd att starta.</p></section>
    </div>
    <section className="cockpit-panel dependency-panel"><div className="panel-title"><div><p className="eyebrow">GEMENSAMMA FÖRUTSÄTTNINGAR</p><h2>Vad behöver bli klart först?</h2></div><Network size={26}/></div><p>Här syns samband över initiativgränser. En möjliggörande leverans kan behöva komma före nästa steg i ett högt prioriterat initiativ.</p>{dependencies.map(d=><article className="dependency-bridge" key={`${d.initiativeId}-${d.node.id}`}><div><span className={`dependency-state ${d.available?"available":"waiting"}`}>{d.available?"Tillgänglig":"Återstår"}</span><button onClick={()=>open(d.ownerInitiativeId,"conditions")}>{state.entities.initiatives[d.ownerInitiativeId].title} <ArrowUpRight size={17}/></button><b>{d.node.title}</b><button className="text-button" onClick={()=>open(d.ownerInitiativeId,"conditions")}>{d.node.responsibleRoleAssignmentId?roleName(state,d.node.responsibleRoleAssignmentId):"Utse ansvarig"} · {d.node.neededAt??"Ange datum"} · hantera förutsättningen</button></div><div className="bridge-relation"><ArrowRight size={27}/><span>{d.beforeStart?"före beroende leverans start":"vid senare milstolpe"}</span></div><div><span className="eyebrow">MÖJLIGGÖR NÄSTA STEG I</span><button onClick={()=>open(d.initiativeId)}>{state.entities.initiatives[d.initiativeId].title} <ArrowUpRight size={17}/></button><p>{d.edges[0].rationale}</p></div></article>)}{!dependencies.length&&<p>Inga registrerade beroenden till andra initiativ i urvalet. Det är inte ett intyg om startklarhet.</p>}<p className="chart-caption">Källa: registrerade leveranser och beroenden. Hantera kopplingarna under Förutsättningar och kostnad i ärendets flöde.</p></section>
    <section className="cockpit-panel activity-panel"><div className="panel-title"><h2>Senast dokumenterat</h2><Activity size={23}/></div>{events.length?<ol>{events.map(e=><li key={e.id}><b>{labels[e.commandType]??"Underlag dokumenterat"}</b><span>{roleName(state,e.actorRoleAssignmentId as RoleAssignmentId)} · {e.issuedAt.slice(0,10)}</span></li>)}</ol>:<p>Ännu inga egna ändringar i sessionen. När ett underlag sparas, ett beslut fattas eller en mätpunkt verifieras syns den dokumenterade händelsen här.</p>}</section>
    <DataProvenance state={state}/>
  </div>;
}
