import { controlRoomCases, selectControlCases, controlStages, type ActionDestination } from '../application/selectors/controlRoomSelectors';
import { ControlProcess, ControlCaseList } from './ControlProcess';
import type { Command,CommandResult } from "../application";
import type { FlowStepKey } from "../application/selectors/flowSelectors";
import { LocationTrail } from "./LocationTrail";
import { CockpitOverview } from "./CockpitOverview";
import type { DemoState } from "../application";
import type { InitiativeId } from "../domain";
import { activeCommitments, committedEconomics, effectOutcome, latestDecision, transformationStage } from "../application/selectors/transformationSelectors";
import { currentEffectPotentials } from "../application/selectors/effectPotentialSelectors";
import { costSummary } from "../application/selectors/costSelectors";
import { Why } from "./transformationUi";
import { format } from "./transformationHelpers";

export interface ControlRoomContext { view:string; stage:string; area:string; from:string; to:string; }
export function ControlRoom({state,day,open,openCases,context,setContext,dispatch,openAction}:{state:DemoState;day:string;open:(id:InitiativeId,section?:FlowStepKey)=>void;openCases:()=>void;context:ControlRoomContext;setContext:(context:ControlRoomContext)=>void;dispatch?:(command:Command)=>CommandResult;openAction?:(target:ActionDestination)=>void}) {
  const {view,stage,area,from,to}=context;
  const setView=(view:string)=>setContext({...context,view});
  const setStage=(stage:string)=>setContext({...context,stage,view:stage==="effects"?"effects":"overview"});
  const setArea=(area:string)=>setContext({...context,area});
  const setFrom=(from:string)=>setContext({...context,from});
  const setTo=(to:string)=>setContext({...context,to});
  const cases=controlRoomCases(state,day,area);
  const selectedCases=selectControlCases(cases,stage);
  const initiativeIds=[...new Set(selectedCases.flatMap(c=>c.initiativeId?[c.initiativeId]:[]))];
  const initiatives=initiativeIds.map(id=>state.entities.initiatives[id]);
  const navigate=(target:ActionDestination)=>{if(openAction)openAction(target);else if(target.initiativeId)open(target.initiativeId,target.section);else openCases();};
  const selectionLabel=controlStages.find(s=>s.key===stage)?.label??(stage==='hinders'?'Hinder som kräver åtgärd':stage==='effects'?'Effekthemtagning':'Alla registrerade ärenden');
  const businesses=area==="Alla"?undefined:Object.values(state.entities.businesses).filter(b=>b.businessAreaId===area).map(b=>b.id);
  const inArea=(businessId?:string)=>area==="Alla"||!!businessId&&!!businesses?.includes(businessId as typeof businesses[number]);
  const economics=committedEconomics(state,initiatives.map(i=>i.id),{from,to},businesses);
  const ids=initiatives.map(i=>i.id),cost=costSummary(state,ids,"ESTIMATE",{from,to});
  const commitments=initiatives.flatMap(i=>activeCommitments(state,i.id)).filter(c=>inArea(c.recipientBusinessId));
  const potentials=initiatives.filter(i=>!latestDecision(state,i.id)).flatMap(i=>currentEffectPotentials(state,i.id)).filter(p=>inArea(p.recipientBusinessId));
  const comparable=commitments.filter(c=>c.details&&c.details.effectWindow.from===from&&c.details.effectWindow.to===to);
  const amount=(category:string,unit:string,kind:"target"|"realized")=>{
    const items=comparable.filter(c=>c.details?.category===category&&c.unit===unit);
    const values=items.map(c=>effectOutcome(state,c,day)[kind]).filter((v):v is number=>v!==undefined);
    return {value:values.length?values.reduce((s,n)=>s+n,0):undefined,count:values.length,total:items.length};
  };
  return <><LocationTrail items={[{label:"Kontrollrum",onClick:view!=="overview"?()=>setView("overview"):undefined},{label:view==="overview"?"Överblick":"Effektuppföljning"}]}/> <div className="control-toolbar"><nav className="cockpit-view-tabs" aria-label="Kontrollrummets vyer"><button aria-pressed={view==="overview"} onClick={()=>setView("overview")}>Överblick</button><button aria-pressed={view==="effects"} onClick={()=>setView("effects")}>Effektuppföljning</button></nav><div className="control-filters"><label>Verksamhetsområde<select value={area} onChange={e=>setArea(e.target.value)}><option value="Alla">Alla områden</option>{Object.values(state.entities.businessAreas).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{view==="effects"&&<><label>Gemensamt effektfönster från<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Till<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}</div></div><ControlProcess cases={cases} selection={stage} onSelect={setStage}/>
    <p className="control-selection" role="status">Visar: {area==="Alla"?"Alla verksamhetsområden":Object.values(state.entities.businessAreas).find(a=>a.id===area)?.name} · {selectionLabel} · {selectedCases.length} ärenden. {view==="effects"?`Effektfönster ${from}–${to}.`:"Antalet ärenden gäller nuläget vid demodatumet, inte ett historiskt portföljurval."}</p>
    <p className="view-purpose">{view==="overview"?"Överblick: var befinner sig arbetet, vad bör prioriteras och vad behöver vår uppmärksamhet?":"Effektuppföljning: vad har verksamheterna åtagit sig, när ska det följas upp och vad visar verifierade mätningar? Område och valt processteg följer med när du växlar vy."}</p>
    {view==="overview"&&stage!=="Alla"&&<ControlCaseList state={state} cases={selectedCases} selection={stage} open={navigate}/>}

    {view==="overview"?<CockpitOverview dispatch={dispatch} area={area} state={state} day={day} ids={ids} open={open} openCases={openCases}/>:<>
    <Why>Totalen är mängden registrerade ärenden, inte summan av potential, åtagande och utfall. Korten nedan räknar endast åtaganden med exakt samma effektfönster och enhet. Pengar som årstakt är inte en ackumulerad besparing. Verifierade mätningar använder senaste mätpunkt per åtagande och jämför med dess egen baseline. Kvalitet hålls per mätetal.</Why>
    <section className="control-metrics">{[["MONEY","SEK/år","Pengar · årstakt","money"],["RELEASED_TIME","timmar/år","Frigjord tid · årstakt","time"],["MONEY","SEK","Pengar · periodbelopp","money"]].map(([category,unit,label,color])=>{const target=amount(category,unit,"target"),actual=amount(category,unit,"realized");return <article className={`card metric-${color}`} key={unit}><h2>{label}</h2><small>Beslutad förbättring</small><b className="big-number">{target.value===undefined?"Inget mål i urvalet":format(target.value)} <small>{target.value===undefined?"":unit}</small></b><small>Verifierad förbättring vid {day}</small><b className="big-number">{format(actual.value)} <small>{actual.value===undefined?"":unit}</small></b><p>{actual.count} av {target.total} åtaganden har verifierad mätning i detta effektfönster.</p></article>})}<article className="card metric-quality"><h2>Kvalitet och skyddsmått</h2><b className="big-number">{commitments.filter(c=>effectOutcome(state,c,day).qualityMet===false).length}</b><p>Verifierade avvikelser mot lokalt beslutad kvalitetsgräns.</p><p>{commitments.filter(c=>effectOutcome(state,c,day).qualityMet===undefined).length} åtaganden saknar verifierad kvalitet.</p></article></section>
    <section className="section-block"><h2>Gemensam investering och lokal förändring</h2><p className="effect-numbers">{format(cost.amount)} SEK <small>bedömd kostnad {from}–{to}</small></p><p>{area!=="Alla"?"Effekter gäller mottagare i valt område. Kostnaden avser hela de berörda initiativen och är inte fördelad per verksamhetsområde; områdesvyerna ska därför inte summeras. ":""}Gemensamma kostnadsposter räknas en gång i urvalet. {cost.completeness==="INCOMPLETE"?"Delår är inte fullständigt beräknade; beloppet är en delsumma.":"Kostnader med angiven period ingår."} Kostnaden jämförs inte automatiskt med årstakten ovan.</p><div className="effect-metrics"><p>Explicit planerad ekonomisk effekt<b>{economics.plannedFinancialEffect===undefined?"Ingen komplett ekonomisk plan i urvalet":`${format(economics.plannedFinancialEffect)} SEK`}</b></p><p>Aktuell kostnadsbedömning i samma period<b>{format(economics.cost)} SEK</b></p><p>Indikativ nettoeffekt<b>{economics.plannedNet===undefined?"Kan inte beräknas":`${format(economics.plannedNet)} SEK`}</b></p></div><p>Ekonomisk plan summerar verksamheternas uttryckliga kalenderårsbelopp. Den är inte realiserad effekt. Kostnaden här är aktuell bedömning; den låsta kostnadsbilden finns i beslutshistoriken. {economics.plannedNet!==undefined&&economics.plannedNet<0?"Kostnaden överstiger den planerade monetära effekten. Skillnaden kräver en tydlig ekonomisk och verksamhetsmässig bedömning.":""}</p><p>{commitments.length-comparable.length} lokala åtaganden har ett annat effektfönster och visas i detalj nedan.</p></section>
    <section className="section-block"><h2>Ärenden och nästa ansvar</h2><div className="table-scroll"><table><thead><tr><th>Ärende</th><th>Skede</th><th>Effektmottagare</th><th>Beslutad förbättring</th><th>Verifierad förbättring</th><th>Nästa mätning / full effekt</th></tr></thead><tbody>{initiatives.map(i=>{const cs=activeCommitments(state,i.id).filter(c=>inArea(c.recipientBusinessId));return <tr key={i.id}><td><button className="text-button" onClick={()=>open(i.id)}>{i.title}</button></td><td>{transformationStage(state,i.id)}</td><td>{cs.map(c=><p key={c.id}>{state.entities.businesses[c.recipientBusinessId].name}<small className="area-label">{state.entities.businessAreas[state.entities.businesses[c.recipientBusinessId].businessAreaId].name}</small></p>)}</td><td>{cs.length?cs.map(c=><p key={c.id}>{c.details?.metricName}: {format(effectOutcome(state,c,day).target)} {effectOutcome(state,c,day).unit}</p>):"Inget beslutat åtagande"}</td><td>{cs.map(c=><p key={c.id}>{format(effectOutcome(state,c,day).realized)} {effectOutcome(state,c,day).realized===undefined?"":effectOutcome(state,c,day).unit}{effectOutcome(state,c,day).qualityMet===false?" · kvalitetsavvikelse":""}</p>)}</td><td>{cs.map(c=>{const missing=c.details?.measurementDates.find(d=>!Object.values(state.entities.measurementPoints).some(m=>m.measurementPlanId===c.measurementPlanId&&m.measuredAt===d&&m.verifiedAt));return <p key={c.id}>{missing??"Mätplan verifierad"}{missing&&missing<day?" · försenad":""} / {c.details?.fullEffectDate}</p>})}</td></tr>})}</tbody></table></div></section>
    <section className="section-block"><h2>Bedömd potential i ingående portfölj</h2><p>Icke bindande. Olika mottagarscenarier, enheter och tidsfönster redovisas var för sig; de är inte en total beslutad besparing.</p><div className="potential-grid">{potentials.map(p=><article className="card" key={p.id}><h3>{state.entities.initiatives[p.initiativeId].title}</h3><p>{p.effectMeasureCode}</p><b>{format(p.lowerBound)}–{format(p.upperBound)} {p.unit}</b><p>Bedömt: {format(p.expectedValue)} · osäkerhet {p.uncertainty}</p><p>{p.realizationWindow} · full potential {p.fullPotentialDate}</p><button onClick={()=>open(p.initiativeId)}>Följ ärendet</button></article>)}</div></section>
  </>}
    {view==="overview"&&stage==="Alla"&&<ControlCaseList state={state} cases={selectedCases} selection={stage} open={navigate}/>}
  </>;
}
