import { LocationTrail } from "./LocationTrail";
import { CockpitOverview } from "./CockpitOverview";
import type { DemoState } from "../application";
import type { InitiativeId } from "../domain";
import { activeCommitments, committedEconomics, effectOutcome, latestDecision, transformationStage } from "../application/selectors/transformationSelectors";
import { currentEffectPotentials } from "../application/selectors/effectPotentialSelectors";
import { costSummary } from "../application/selectors/costSelectors";
import { Why } from "./transformationUi";
import { format } from "./transformationHelpers";

export interface ControlRoomContext { view:string; stage:string; area:string; from:string; to:string; }
export function ControlRoom({state,day,open,openCases,context,setContext}:{state:DemoState;day:string;open:(id:InitiativeId,section?:"potential")=>void;openCases:()=>void;context:ControlRoomContext;setContext:(context:ControlRoomContext)=>void}) {
  const {view,stage,area,from,to}=context;
  const setView=(view:string)=>setContext({...context,view});
  const setStage=(stage:string)=>setContext({...context,stage});
  const setArea=(area:string)=>setContext({...context,area});
  const setFrom=(from:string)=>setContext({...context,from});
  const setTo=(to:string)=>setContext({...context,to});
  const stages=["Alla","Under beredning","Pågående","Under mätning","Avslutat"];
  const all=Object.values(state.entities.initiatives).filter(i=>area==="Alla"||Object.values(state.entities.participations).some(p=>p.initiativeId===i.id&&p.businessId&&state.entities.businesses[p.businessId]?.businessAreaId===area));
  const initiatives=all.filter(i=>stage==="Alla"||transformationStage(state,i.id)===stage);
  const economics=committedEconomics(state,initiatives.map(i=>i.id),{from,to});
  const ids=initiatives.map(i=>i.id),cost=costSummary(state,ids,"ESTIMATE",{from,to});
  const commitments=initiatives.flatMap(i=>activeCommitments(state,i.id));
  const potentials=initiatives.filter(i=>!latestDecision(state,i.id)).flatMap(i=>currentEffectPotentials(state,i.id));
  const comparable=commitments.filter(c=>c.details&&c.details.effectWindow.from===from&&c.details.effectWindow.to===to);
  const amount=(category:string,unit:string,kind:"target"|"realized")=>{
    const items=comparable.filter(c=>c.details?.category===category&&c.unit===unit);
    const values=items.map(c=>effectOutcome(state,c,day)[kind]).filter((v):v is number=>v!==undefined);
    return {value:values.length?values.reduce((s,n)=>s+n,0):undefined,count:values.length,total:items.length};
  };
  return <><LocationTrail items={[{label:"Kontrollrum",onClick:view!=="overview"?()=>setView("overview"):undefined},{label:view==="overview"?"Överblick":"Effektuppföljning"}]}/> <section className="hero cockpit-hero"><div><p className="eyebrow">KONTROLLRUM · FRÅN MÖJLIGHET TILL EFFEKT</p><h1>Gemensam riktning. Synliga framsteg.</h1><p className="lead">Se vad som kan skapa värde, vad som behöver hända först och vem som tar nästa steg.</p></div></section><nav className="cockpit-view-tabs" aria-label="Kontrollrummets vyer"><button aria-pressed={view==="overview"} onClick={()=>setView("overview")}>Överblick</button><button aria-pressed={view==="effects"} onClick={()=>setView("effects")}>Effektuppföljning</button></nav><div className="control-filters"><label>Verksamhetsområde<select value={area} onChange={e=>setArea(e.target.value)}><option value="Alla">Alla områden</option>{Object.values(state.entities.businessAreas).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{view==="effects"&&<><label>Gemensamt effektfönster från<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Till<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></>}</div><nav className="stage-counters" aria-label="Portföljens skeden">{stages.map(s=><button key={s} aria-pressed={s===stage} onClick={()=>setStage(s)}><span>{s==="Alla"?"Total portfölj":s}</span><b>{s==="Alla"?all.length:all.filter(i=>transformationStage(state,i.id)===s).length}</b></button>)}</nav>
    {view==="overview"?<CockpitOverview state={state} day={day} ids={ids} open={open} openCases={openCases}/>:<>
    <Why>Total portfölj är mängden ärenden, inte summan av potential, åtagande och utfall. Korten nedan räknar endast åtaganden med exakt samma effektfönster och enhet. Pengar som årstakt är inte en ackumulerad besparing. Verifierade mätningar använder senaste mätpunkt per åtagande och jämför med dess egen baseline. Kvalitet hålls per mätetal.</Why>
    <section className="control-metrics">{[["MONEY","SEK/år","Pengar · årstakt","money"],["RELEASED_TIME","timmar/år","Frigjord tid · årstakt","time"],["MONEY","SEK","Pengar · periodbelopp","money"]].map(([category,unit,label,color])=>{const target=amount(category,unit,"target"),actual=amount(category,unit,"realized");return <article className={`card metric-${color}`} key={unit}><h2>{label}</h2><small>Beslutad förbättring</small><b className="big-number">{format(target.value)} <small>{target.value===undefined?"":unit}</small></b><small>Verifierad förbättring vid {day}</small><b className="big-number">{format(actual.value)} <small>{actual.value===undefined?"":unit}</small></b><p>{actual.count} av {target.total} åtaganden har verifierad mätning i detta effektfönster.</p></article>})}<article className="card metric-quality"><h2>Kvalitet och skyddsmått</h2><b className="big-number">{commitments.filter(c=>effectOutcome(state,c,day).qualityMet===false).length}</b><p>Verifierade avvikelser mot lokalt beslutad kvalitetsgräns.</p><p>{commitments.filter(c=>effectOutcome(state,c,day).qualityMet===undefined).length} åtaganden saknar verifierad kvalitet.</p></article></section>
    <section className="section-block"><h2>Gemensam investering och lokal förändring</h2><p className="effect-numbers">{format(cost.amount)} SEK <small>bedömd kostnad {from}–{to}</small></p><p>Gemensamma kostnadsposter räknas en gång i urvalet. {cost.completeness==="INCOMPLETE"?"Delår är inte fullständigt beräknade; beloppet är en delsumma.":"Kostnader med angiven period ingår."} Kostnaden jämförs inte automatiskt med årstakten ovan.</p><div className="effect-metrics"><p>Explicit planerad ekonomisk effekt<b>{format(economics.plannedFinancialEffect)} SEK</b></p><p>Aktuell kostnadsbedömning i samma period<b>{format(economics.cost)} SEK</b></p><p>Indikativ nettoeffekt<b>{format(economics.plannedNet)} SEK</b></p></div><p>Ekonomisk plan summerar verksamheternas uttryckliga kalenderårsbelopp. Den är inte realiserad effekt. Kostnaden här är aktuell bedömning; den låsta kostnadsbilden finns i beslutshistoriken. {economics.plannedNet!==undefined&&economics.plannedNet<0?"Kostnaden överstiger den planerade monetära effekten. Skillnaden kräver en tydlig ekonomisk och verksamhetsmässig bedömning.":""}</p><p>{commitments.length-comparable.length} lokala åtaganden har ett annat effektfönster och visas i detalj nedan.</p></section>
    <section className="section-block"><h2>Ärenden och nästa ansvar</h2><div className="table-scroll"><table><thead><tr><th>Ärende</th><th>Skede</th><th>Effektmottagare</th><th>Beslutad förbättring</th><th>Verifierad förbättring</th><th>Nästa mätning / full effekt</th></tr></thead><tbody>{initiatives.map(i=>{const cs=activeCommitments(state,i.id);return <tr key={i.id}><td><button className="text-button" onClick={()=>open(i.id)}>{i.title}</button></td><td>{transformationStage(state,i.id)}</td><td>{cs.map(c=><p key={c.id}>{state.entities.businesses[c.recipientBusinessId].name}</p>)}</td><td>{cs.length?cs.map(c=><p key={c.id}>{c.details?.metricName}: {format(effectOutcome(state,c,day).target)} {effectOutcome(state,c,day).unit}</p>):"Inget beslutat åtagande"}</td><td>{cs.map(c=><p key={c.id}>{format(effectOutcome(state,c,day).realized)} {effectOutcome(state,c,day).realized===undefined?"":effectOutcome(state,c,day).unit}{effectOutcome(state,c,day).qualityMet===false?" · kvalitetsavvikelse":""}</p>)}</td><td>{cs.map(c=>{const missing=c.details?.measurementDates.find(d=>!Object.values(state.entities.measurementPoints).some(m=>m.measurementPlanId===c.measurementPlanId&&m.measuredAt===d&&m.verifiedAt));return <p key={c.id}>{missing??"Mätplan verifierad"}{missing&&missing<day?" · försenad":""} / {c.details?.fullEffectDate}</p>})}</td></tr>})}</tbody></table></div></section>
    <section className="section-block"><h2>Bedömd potential i ingående portfölj</h2><p>Icke bindande. Olika mottagarscenarier, enheter och tidsfönster redovisas var för sig; de är inte en total beslutad besparing.</p><div className="potential-grid">{potentials.map(p=><article className="card" key={p.id}><h3>{state.entities.initiatives[p.initiativeId].title}</h3><p>{p.effectMeasureCode}</p><b>{format(p.lowerBound)}–{format(p.upperBound)} {p.unit}</b><p>Bedömt: {format(p.expectedValue)} · osäkerhet {p.uncertainty}</p><p>{p.realizationWindow} · full potential {p.fullPotentialDate}</p><button onClick={()=>open(p.initiativeId)}>Följ ärendet</button></article>)}</div></section>
  </>}
  </>;
}
