import { CopilotHelp } from "./CopilotHelp";
import { useEffect, useState } from "react";
import { downloadBlob, parseDocument, portableDocument, type DocumentEnvelope, type DocumentField } from "./documentFormat";
import { readDocuments, writeDocuments, type StoredDocumentFile } from "./documentStore";

export function DocumentPanel({kind,caseId,title,purpose,fields,values,onImport}:{kind:string;caseId:string;title:string;purpose:string;fields:DocumentField[];values:Record<string,string>;onImport?:(values:Record<string,string>)=>void}) {
 const key=`${caseId}/${kind}`;
 const [files,setFiles]=useState<StoredDocumentFile[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let active=true;setLoaded(false);setFiles([]);if(typeof indexedDB!=="undefined")readDocuments(key).then(x=>{if(active){setFiles(x.files);setLoaded(true);}}).catch(()=>{if(active)setMessage("Lokal dokumentlagring kunde inte öppnas. Du kan fortfarande ladda ner dokumentet.");});return()=>{active=false;};},[key]);
 const envelope=(empty=false):DocumentEnvelope=>({format:"cockpit-document",version:1,kind,caseId:empty?"":caseId,values:empty?{}:values});
 const save=async(file:StoredDocumentFile)=>{if(files.length>=30)throw Error("Högst 30 filer per dokument i demon.");const next=[...files,file];await writeDocuments({key,files:next});setFiles(next);};
 const upload=async(file:File)=>{setBusy(true);try{if(file.size>10*1024*1024)throw Error("Filen är för stor för demon. Högst 10 MB per fil.");if(files.length>=30)throw Error("Högst 30 filer per dokument i demon.");if(/\.json$/i.test(file.name)&&onImport){const imported=parseDocument(await file.text(),kind,caseId,fields);await save({id:crypto.randomUUID(),name:file.name,createdAt:new Date().toISOString(),blob:file});onImport(imported);setMessage("Uppladdat och inläst som utkast. Kontrollera uppgifterna och spara i formuläret. Inga krav, accepteranden eller beslut har godkänts.");}else{await save({id:crypto.randomUUID(),name:file.name,createdAt:new Date().toISOString(),blob:file});setMessage("Bilagan är sparad vid detta dokument. Innehållet har inte tolkats eller godkänts. Komplettera och granska formuläret.");}}catch(e){setMessage(e instanceof Error?e.message:"Dokumentet kunde inte sparas.");}finally{setBusy(false);}};
 return <section className="document-panel" aria-label={`Dokument: ${title}`}><p className="eyebrow">AVGRÄNSAT DOKUMENT · {title}</p><p>{purpose}</p><CopilotHelp key={key} section={title} context={`I utkastet: ${fields.filter(f=>f.required&&!values[f.key]?.trim()).map(f=>f.label).join(", ")||"alla obligatoriska textfält har innehåll"}. Uppgifterna måste fortfarande granskas och sparas i processen.`} fields={fields} values={values} onApply={onImport?patch=>onImport({...values,...patch}):undefined}/><details className="document-files"><summary>Mall, dokumentkopior och bilagor · {files.length}</summary><div className="document-actions"><button type="button" onClick={()=>downloadBlob(new Blob([portableDocument(title,purpose,envelope(true),fields)],{type:"text/html;charset=utf-8"}),`${kind}-mall.html`)}>Ladda ner mall</button><button type="button" onClick={()=>downloadBlob(new Blob([portableDocument(title,purpose,envelope(),fields)],{type:"text/html;charset=utf-8"}),`${kind}-dokument.html`)}>Ladda ner aktuellt dokument</button><button type="button" disabled={!loaded||busy} onClick={async()=>{setBusy(true);try{await save({id:crypto.randomUUID(),name:`${title} – dokumentkopia.json`,createdAt:new Date().toISOString(),blob:new Blob([JSON.stringify(envelope(),null,2)],{type:"application/json"})});setMessage("Dokumentkopian är sparad lokalt. Detta är ingen registrering eller accept i processen.");}catch{setMessage("Dokumentkopian kunde inte sparas. Ladda ner dokumentet i stället.");}finally{setBusy(false);}}}>Spara lokal dokumentkopia</button></div><label className="document-upload">Ladda upp ifylld mall eller bilaga<input type="file" disabled={!loaded||busy} accept=".json,.pdf,.docx,.xlsx,.txt,.html" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value="";}}/></label><p role="status">{message}</p><details><summary>Sparade dokument och bilagor · {files.length}</summary>{files.map(f=><p key={f.id}><button type="button" className="text-button" onClick={()=>downloadBlob(f.blob,f.name)}>{f.name}</button> · {new Date(f.createdAt).toLocaleString("sv-SE")}{onImport&&f.name.toLowerCase().endsWith(".json")&&<button type="button" onClick={async()=>{try{onImport(parseDocument(await f.blob.text(),kind,caseId,fields));setMessage("Dokumentkopian återläst som utkast. Kontrollera och registrera via formuläret.");}catch(e){setMessage(String(e));}}}>Återläs utkast</button>}</p>)}</details><p className="template-note">Fyll i online i formuläret nedan, eller öppna HTML-mallen i webbläsaren och spara dess JSON-fil för återläsning. PDF, Word och övriga filer är bilagor som granskas manuellt. Dokument sparas i denna webbläsare; de delas inte mellan användare. Demosessionens processdata sparas separat. En fil gör aldrig ett krav grönt.</p></details></section>;
}
