import { act, create, type ReactTestInstance } from "react-test-renderer";
import { expect, it } from "vitest";
import App from "../App";
import { referenceCommitment } from "../demo-data/referenceCommitment";
import { roleAssignments } from "../demo-data/peopleAndRoles";

const text=(n:unknown):string=>typeof n==="string"?n:n&&typeof n==="object"&&"children" in n?(n as {children:unknown[]}).children.map(text).join(""):"";
it("går genom synliga formulär från lokalt utkast till start, verifierad mätning och kontrollrum",()=>{
  const renderer=create(<App/>),root=renderer.root;
  const button=(name:string)=>root.findAllByType("button").find(b=>text(b)===name)!;
  const click=(name:string)=>act(()=>button(name).props.onClick());
  const control=(label:string,kind:"input"|"select"="input")=>root.findAllByType("label").find(l=>text(l).startsWith(label))!.findByType(kind);
  const enter=(label:string,value:string,kind:"input"|"select"="input")=>act(()=>control(label,kind).props.onChange({target:{value}}));
  const check=(label:string)=>act(()=>control(label).props.onChange({target:{checked:true}}));
  const submit=(name:string)=>{let form:ReactTestInstance|null=button(name);while(form&&form.type!=="form")form=form.parent;act(()=>form!.props.onSubmit({preventDefault(){}}));};
  click("Effekt och beslut");enter("Välj ärende",referenceCommitment.initiativeId,"select");
  click("Fyll formuläret med syntetiskt avtalsexempel");
  enter("Person som dokumenterar utkastet",roleAssignments[1].id,"select");
  check("Baseline är kontrollerad");submit("Spara åtagandeutkast");
  expect(text(root)).toContain("Utkast – inte accepterat");
  enter("Jag agerar som effektägare",referenceCommitment.details.ownerRoleAssignmentId,"select");
  enter("Mandat att binda", "Syntetiskt verksamhetsmandat");check("Jag accepterar aktivt");submit("Acceptera lokalt effektåtagande");
  expect(text(root)).toContain("Aktivt accepterat");
  enter("Ny mottagande verksamhet",referenceCommitment.businessId,"select");enter("Person som registrerar deltagandet",roleAssignments[1].id,"select");submit("Lägg till effektmottagare");
  click("2. Start och beslut");
  const priority=control("Prioriteringsunderlag","select").findAllByType("option")[1].props.value;
  enter("Prioriteringsunderlag",priority,"select");enter("Styrversion","GOVERNANCE-DEMO-1","select");
  for(const label of ["Finansiering –", "Genomförandekapacitet –", "Lagkrav och", "Kvalitetskrav –", "Beroenden –", "Samlad ekonomi –"])enter(label,"Syntetisk dokumenterad bedömning för detta ärende");
  enter("Ekonomisk jämförelse till","2027-12-31");
  enter("Beslutsfattare (demo)",roleAssignments[2].id,"select");
  const commitmentChoice=root.findAllByType("input").find(i=>i.props.type==="checkbox")!;
  act(()=>commitmentChoice.props.onChange({target:{checked:true}}));
  submit("Spara nytt beslutspaket och pröva startklarhet");
  expect(text(root)).toContain("Underlaget är komplett");
  enter("Beslutsmotivering","Syntetiskt aktivt startbeslut");check("Jag fattar aktivt beslut");submit("Fatta startbeslut");
  click("4. Beslutshistorik");expect(text(root)).toContain("Beslutsversion 1");expect(text(root)).toContain("Syntetiskt aktivt startbeslut");
  click("3. Förändring och mätning");enter("Demodatum","2026-12-31");
  enter("Aktiv person för",referenceCommitment.details.changeResponsibleId,"select");enter("Förändringen genomförd","2026-12-31");enter("Evidens för att arbetssättet","Syntetisk rutin används");submit("Bekräfta genomförd förändring");
  enter("Demodatum","2027-12-31");enter("Beslutad mättidpunkt","2027-12-31","select");enter("Uppmätt nivå","450000");enter("Mätunderlag och evidens","Syntetiskt mätuttag");enter("Uppmätt kvalitet och underlag","Alla kritiska tjänster omfattas");enter("Uppfylls beslutad kvalitetsgräns?","yes","select");submit("Rapportera mätpunkt för verifiering");
  expect(text(root)).toContain("Ej uppmätt");
  enter("Aktiv person för",roleAssignments[1].id,"select");check("Jag har kontrollerat mätningen");click("Verifiera mätpunkt som specialist");
  expect(text(root)).toMatch(/150\s000/);
  click("Kontrollrum");expect(text(root)).toContain("Digital fiktiv avtalsuppföljning");expect(text(root)).toContain("Under mätning");expect(text(root)).toMatch(/150\s000/);
});
