import { referenceCommitment } from "../demo-data/referenceCommitment";
import { useState } from "react";
import { createId, type BusinessId, type EffectCommitmentId, type InitiativeId, type LocalEffectCommitment, type PriorityAssessmentId, type RoleAssignmentId } from "../domain";
import type { Command } from "../application";
import { acceptedCommitment, activeCommitments, commitmentBlockers, effectOutcome, latestDecision, preparedEconomics, startBlockers, transformationStage } from "../application/selectors/transformationSelectors";
import { Blockers, Field, RoleSelect, Why, type WorkProps } from "./transformationUi";
import { format, roleName, token } from "./transformationHelpers";

export function EffectWorkspace(props: WorkProps & {initialId?:InitiativeId;openCase:(id:InitiativeId)=>void}) {
  const [id,setId]=useState(props.initialId??Object.values(props.state.entities.initiatives)[0].id);
  return <><section className="hero"><div><p className="eyebrow">FRÅN MÖJLIG EFFEKT TILL VERIFIERAT UTFALL</p><h1>Verksamheten äger effekten</h1><p className="lead">Ett lokalt löfte, ett mänskligt beslut och en mätning mot det som faktiskt beslutades.</p></div></section><label className="case-picker">Välj ärende<select value={id} onChange={e=>setId(e.target.value as InitiativeId)}>{Object.values(props.state.entities.initiatives).map(i=><option key={i.id} value={i.id}>{i.title} · {transformationStage(props.state,i.id)}</option>)}</select></label><button className="secondary-action" onClick={()=>props.openCase(id)}>Visa utmaning och businesscase</button><EffectCase key={id} {...props} id={id}/></>;
}

function EffectCase({state,dispatch,day,id}:WorkProps & {id:InitiativeId}) {
  const [tab,setTab]=useState("commitments"),[feedback,setFeedback]=useState("");
  const send=(c:Command)=>{const r=dispatch(c);setFeedback(r.success?"Sparat. Samma underlag följer med genom ärendet.":r.errors.map(e=>e.description).join(" "));return r;};
  const props={state,dispatch:send,day};
  const commitments=Object.values(state.entities.effectCommitments).filter(c=>c.initiativeId===id);
  const versions=Object.values(state.entities.decisionVersions).filter(v=>v.initiativeId===id).sort((a,b)=>b.versionNumber-a.versionNumber);
  return <section className="section-block"><nav className="work-tabs" aria-label="Effektkedja">{[["commitments","1. Lokala åtaganden"],["decision","2. Start och beslut"],["measurement","3. Förändring och mätning"],["history","4. Beslutshistorik"]].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav><p role="status" className="feedback">{feedback}</p>
    {tab==="commitments"&&<><h2>Beslutad effekthemtagning per verksamhet</h2><Why>Potentialen hjälper oss att prioritera. Här anger varje mottagande verksamhet själv vilket utfall den åtar sig, vilka förändringar som krävs och vem som ansvarar. Syntetiska roller används för att demonstrera aktiva handlingar; verklig autentisering är inte ansluten.</Why><RecipientForm {...props} id={id}/><CommitmentForm {...props} id={id}/>{commitments.map(c=><CommitmentCard key={c.id} {...props} commitment={c}/>)}</>}
    {tab==="decision"&&<DecisionForm {...props} id={id}/>}
    {tab==="measurement"&&<><h2>Förändra, mät och verifiera</h2><Why>Teknik och projektleverans möjliggör förändring. Realiserad effekt visas först när en beslutad lokal mätpunkt har rapporterats och verifierats. Prognoser ändrar aldrig målet.</Why>{!versions.length&&<p className="gate blocked">Inget startbeslut finns. Slutför lokala åtaganden och pröva startklarheten först.</p>}{activeCommitments(state,id).map(c=><MeasurementCard key={c.id} {...props} commitment={c}/>)}{versions.length>0&&<CloseForm {...props} id={id}/>}</>}
    {tab==="history"&&<><h2>Låsta beslutsbaslinjer</h2><p>Varje version bevarar då gällande åtaganden, baseline, mätplan, accept, prioritering, kostnadsunderlag, styrning och beroenden. Ett ändringsbeslut ersätter aldrig originalet.</p>{!versions.length&&<p>Ingen beslutsbaslinje är låst ännu.</p>}{versions.map(v=>{const decision=state.entities.humanDecisions[v.humanDecisionId];const cs=v.snapshot.commitments as LocalEffectCommitment[];return <article className="card" key={v.id}><h3>Beslutsversion {v.versionNumber} · {decision.decisionType==="START"?"Startbeslut":"Ändringsbeslut"}</h3><p>{decision.decidedAt.slice(0,10)} · {roleName(state,decision.decisionMakerRoleAssignmentId)}</p><p>{decision.rationale}</p>{cs.map(c=><p key={c.id}>{state.entities.businesses[c.recipientBusinessId].name}: {c.details?.metricName} → mål {format(c.targetValue)} {c.unit} · full effekt {c.details?.fullEffectDate}</p>)}<details className="trace"><summary>Visa hela det låsta beslutsunderlaget</summary><pre className="snapshot">{JSON.stringify(v.snapshot,null,2)}</pre></details></article>})}</>}
  </section>;
}

function RecipientForm({state,dispatch,day,id}:WorkProps & {id:InitiativeId}) {
  const [business,setBusiness]=useState(""),[actor,setActor]=useState<RoleAssignmentId|"">("");
  const recipients=Object.values(state.entities.participations).filter(p=>p.initiativeId===id&&p.participantKind==="EFFECT_RECIPIENT"&&p.validFrom<=day&&(!p.validTo||p.validTo>=day));
  return <details className="card"><summary>Deltagande effektmottagare · {recipients.length}</summary><p>{recipients.map(p=>state.entities.businesses[p.businessId!]?.name).join(", ")||"Ingen utsedd ännu"}</p><p>En tillkommande verksamhet behöver ett eget åtagande. Vid skalning efter start krävs också ett ändringsbeslut.</p><form className="edit-panel" onSubmit={e=>{e.preventDefault();const b=Object.values(state.entities.businesses).find(x=>x.id===business);if(!b||!actor)return;dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"ADD_PARTICIPATION",targetId:createId("Participation",token()),payload:{initiativeId:id,organizationId:b.organizationId,businessId:b.id,participantKind:"EFFECT_RECIPIENT",validFrom:day}});}}><label>Ny mottagande verksamhet<select required value={business} onChange={e=>setBusiness(e.target.value)}><option value="">Välj verksamhet</option>{Object.values(state.entities.businesses).filter(b=>!recipients.some(p=>p.businessId===b.id)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><RoleSelect state={state} label="Person som registrerar deltagandet" value={actor} onChange={setActor}/><button>Lägg till effektmottagare</button></form></details>;
}

const emptyCommitment={metricName:"",scope:"",category:"MONEY",unit:"SEK/år",direction:"LOWER_IS_BETTER",baseline:"",target:"",baselineDate:"",baselineReference:"",dataSource:"",changeDescription:"",changeDueDate:"",receiverCapacity:"",measurementDates:"",fullEffectDate:"",from:"",to:"",qualitySafeguard:"",qualityLimit:"",annualFinancialEffect:""};
function CommitmentForm({state,dispatch,day,id}:WorkProps & {id:InitiativeId}) {
  const [form,setForm]=useState(emptyCommitment),[business,setBusiness]=useState<BusinessId|"">(""),[owner,setOwner]=useState<RoleAssignmentId|"">(""),[change,setChange]=useState<RoleAssignmentId|"">(""),[measure,setMeasure]=useState<RoleAssignmentId|"">(""),[author,setAuthor]=useState<RoleAssignmentId|"">(""),[verified,setVerified]=useState(false),[supersedes,setSupersedes]=useState<EffectCommitmentId|"">("");
  const field=(key:keyof typeof form,label:string,type="text")=><Field key={key} label={label} value={form[key]} type={type} onChange={v=>setForm({...form,[key]:v})}/>;
  const fillExample=()=>{const p=referenceCommitment,d=p.details;setBusiness(p.businessId);setOwner(d.ownerRoleAssignmentId);setChange(d.changeResponsibleId);setMeasure(p.measurementResponsibleId);setVerified(false);setForm({metricName:d.metricName,scope:d.scope,category:d.category,unit:p.unit,direction:p.direction,baseline:String(p.baseline),target:String(p.target),baselineDate:p.baselineDate,baselineReference:d.baselineReference,dataSource:p.dataSource,changeDescription:d.changeDescription,changeDueDate:d.changeDueDate,receiverCapacity:d.receiverCapacity,measurementDates:d.measurementDates.join(", "),fullEffectDate:d.fullEffectDate,from:d.effectWindow.from,to:d.effectWindow.to,qualitySafeguard:d.qualitySafeguard,qualityLimit:d.qualityLimit,annualFinancialEffect:d.annualFinancialEffect?.map(x=>`${x.year}:${x.amount}`).join(", ")??""});};
  return <details className="card"><summary>Skapa lokalt åtagande eller ny åtagandeversion</summary><p>Du kan skriva ett eget fiktivt underlag. För avtalsexemplet finns också en ifyllnadshjälp; den bekräftar ingen baseline och accepterar inget åtagande.</p>{id===referenceCommitment.initiativeId&&<button className="secondary-action" onClick={fillExample}>Fyll formuläret med syntetiskt avtalsexempel</button>}<form className="commitment-form" onSubmit={e=>{e.preventDefault();if(!business||!owner||!change||!measure||!author)return;dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:author,issuedAt:`${day}T12:00:00Z`,commandType:"SAVE_EFFECT_COMMITMENT",targetId:createId("EffectCommitment",token()),payload:{initiativeId:id,businessId:business,target:Number(form.target),baseline:Number(form.baseline),baselineDate:form.baselineDate,baselineVerified:verified,unit:form.unit,direction:form.direction as "LOWER_IS_BETTER"|"HIGHER_IS_BETTER",dataSource:form.dataSource,measurementResponsibleId:measure,details:{category:form.category as "MONEY",metricName:form.metricName,scope:form.scope,changeDescription:form.changeDescription,changeResponsibleId:change,changeDueDate:form.changeDueDate,receiverCapacity:form.receiverCapacity,measurementDates:form.measurementDates.split(/[,\n]/).map(s=>s.trim()).filter(Boolean).sort(),fullEffectDate:form.fullEffectDate,effectWindow:{from:form.from,to:form.to},ownerRoleAssignmentId:owner,baselineReference:form.baselineReference,qualitySafeguard:form.qualitySafeguard,qualityLimit:form.qualityLimit,annualFinancialEffect:form.category==="MONEY"?form.annualFinancialEffect.split(",").filter(x=>x.trim()).map(x=>{const [year,amount]=x.split(":");return {year:Number(year),amount:Number(amount)};}):undefined,supersedesId:supersedes||undefined}}});}}>
    <fieldset><legend>1. Verksamhetens effekt och omfattning</legend><div className="form-grid"><label>Effektmottagande verksamhet<select required value={business} onChange={e=>{setBusiness(e.target.value as BusinessId);setOwner("");}}><option value="">Välj verksamhet</option>{Object.values(state.entities.businesses).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Ny version av tidigare åtagande<select value={supersedes} onChange={e=>setSupersedes(e.target.value as EffectCommitmentId)}><option value="">Ett nytt lokalt åtagande</option>{Object.values(state.entities.effectCommitments).filter(c=>c.initiativeId===id&&c.recipientBusinessId===business).map(c=><option key={c.id} value={c.id}>{c.details?.metricName} · version {c.details?.version}</option>)}</select></label><label>Effektkategori<select value={form.category} onChange={e=>setForm({...form,category:e.target.value,unit:e.target.value==="MONEY"?"SEK/år":e.target.value==="RELEASED_TIME"?"timmar/år":"procent"})}><option value="MONEY">Pengar</option><option value="RELEASED_TIME">Frigjord tid</option><option value="QUALITY">Kvalitet</option><option value="OTHER_BUSINESS_EFFECT">Annan verksamhetseffekt</option></select></label>{field("metricName","Mätetal")}{field("scope","Omfattning – vilken del av verksamheten?")}{field("unit","Enhet")}<label>Önskad riktning<select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="LOWER_IS_BETTER">Lägre värde är bättre</option><option value="HIGHER_IS_BETTER">Högre värde är bättre</option></select></label>{field("target","Beslutat målvärde (nivå, inte förbättring)","number")}{form.category==="MONEY"&&field("annualFinancialEffect","Planerad ekonomisk effekt per kalenderår – t.ex. 2027:150000, 2028:180000")}</div></fieldset>
    <fieldset><legend>2. Baseline och verifierbar mätning</legend><div className="form-grid">{field("baseline","Lokalt utgångsvärde", "number")}{field("baselineDate","Baseline uppmätt", "date")}{field("baselineReference","Baselineunderlag")}{field("dataSource","Datakälla och uttag")}{field("measurementDates","Mättidpunkter – YYYY-MM-DD, separerade med komma")}{field("fullEffectDate","Bedömning av full effekt", "date")}{field("from","Effektfönster från", "date")}{field("to","Effektfönster till", "date")}<RoleSelect state={state} label="Mätningsansvarig" value={measure} onChange={setMeasure}/></div><label className="check"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Baseline är kontrollerad mot angivet underlag.</label></fieldset>
    <fieldset><legend>3. Förändring, kapacitet och kvalitet</legend><div className="form-grid">{field("changeDescription","Nödvändig verksamhetsförändring")}<RoleSelect state={state} label="Ansvarig för verksamhetsförändringen" value={change} onChange={setChange}/>{field("changeDueDate","Förändringen ska vara genomförd", "date")}{field("receiverCapacity","Bekräftad mottagarkapacitet – resurser och avsatt tid")}{field("qualitySafeguard","Kvalitets- eller skyddsmått")}{field("qualityLimit","Godtagbar kvalitetsgräns")}</div></fieldset>
    <fieldset><legend>4. Namngivna roller</legend><div className="form-grid"><RoleSelect state={state} label="Lokal effektägare med mandat" kind="OWNER" businessId={business||"not-selected"} value={owner} onChange={setOwner}/><RoleSelect state={state} label="Person som dokumenterar utkastet" value={author} onChange={setAuthor}/></div><p>Att dokumentera skapar ett utkast. Den lokala effektägaren accepterar det separat nedan. IT och metodstöd kan aldrig acceptera för verksamheten.</p></fieldset><button>Spara åtagandeutkast</button>
  </form></details>;
}

function CommitmentCard({state,dispatch,day,commitment:c}:WorkProps & {commitment:LocalEffectCommitment}) {
  const [actor,setActor]=useState<RoleAssignmentId|"">(""),[accepted,setAccepted]=useState(false),[mandate,setMandate]=useState("");
  const acceptance=acceptedCommitment(state,c.id),d=c.details!,baseline=state.entities.baselines[c.baselineId],blockers=commitmentBlockers(state,c,day);
  return <article className="card commitment-card"><span className="category">{acceptance?"Aktivt accepterat":"Utkast – inte accepterat"} · version {d?.version}</span><h3>{state.entities.businesses[c.recipientBusinessId].name} · {d?.metricName}</h3><p className="effect-numbers">{format(baseline.value)} → {format(c.targetValue)} <small>{c.unit}</small></p><p>{d?.scope}</p><dl><dt>Effektägare</dt><dd>{roleName(state,d?.ownerRoleAssignmentId)}</dd><dt>Förändring</dt><dd>{d?.changeDescription} · {d?.changeDueDate}</dd><dt>Förändringsansvarig</dt><dd>{roleName(state,d?.changeResponsibleId)}</dd><dt>Mätning</dt><dd>{d?.measurementDates.join(", ")} · {roleName(state,state.entities.measurementPlans[c.measurementPlanId].responsibleRoleAssignmentId)}</dd><dt>Ekonomisk plan</dt><dd>{d?.annualFinancialEffect?.map(x=>`${x.year}: ${format(x.amount)} SEK`).join(" · ")??"Ingen monetär plan"}</dd><dt>Full effekt</dt><dd>{d?.fullEffectDate}</dd><dt>Kvalitet</dt><dd>{d?.qualitySafeguard}: {d?.qualityLimit}</dd></dl>{blockers.length>0&&<ul className="validation-errors">{blockers.map(b=><li key={b}>{b}</li>)}</ul>}{acceptance?<p>Accepterat {acceptance.acceptedAt.slice(0,10)} · {acceptance.mandateDescription}</p>:<form className="edit-panel" onSubmit={e=>{e.preventDefault();if(actor)dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"ACCEPT_EFFECT_COMMITMENT",targetId:c.id,payload:{accepted,mandateDescription:mandate}});}}><RoleSelect state={state} label="Jag agerar som effektägare (demo)" kind="OWNER" value={actor} onChange={setActor}/><Field label="Mandat att binda den egna verksamheten" value={mandate} onChange={setMandate}/><label className="check"><input required type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Jag accepterar aktivt effekt, lokal baseline, förändring, kapacitet och mätplan.</label><button>Acceptera lokalt effektåtagande</button></form>}</article>;
}

function DecisionForm({state,dispatch,day,id}:WorkProps & {id:InitiativeId}) {
  const [form,setForm]=useState({fundingReference:"",capacityReference:"",legalReference:"",qualityReference:"",prerequisitesReview:"",economicRationale:"",from:"2026-01-01",to:"2030-12-31"}),[selected,setSelected]=useState<EffectCommitmentId[]>([]),[priority,setPriority]=useState<PriorityAssessmentId|"">(""),[governance,setGovernance]=useState(""),[actor,setActor]=useState<RoleAssignmentId|"">(""),[accepted,setAccepted]=useState(false),[rationale,setRationale]=useState(""),[impacts,setImpacts]=useState({cost:"",time:"",quality:"",effect:""});
  const packages=Object.values(state.entities.startPreparations).filter(p=>p.initiativeId===id);const preparation=packages[packages.length-1],old=latestDecision(state,id);
  const assessments=Object.values(state.entities.priorityAssessments).filter(a=>a.initiativeId===id);
  const commitments=Object.values(state.entities.effectCommitments).filter(c=>c.initiativeId===id);
  const labels={fundingReference:"Finansiering – bedömning och underlag",capacityReference:"Genomförandekapacitet – personer och tid",legalReference:"Lagkrav och informationssäkerhet – bedömning och underlag",qualityReference:"Kvalitetskrav – gränser och underlag",prerequisitesReview:"Beroenden – vad måste finnas före start?",economicRationale:"Samlad ekonomi – effekt och kostnad i samma tidsfönster"};
  return <><h2>{old?"Ändringsprövning":"Samlat beslutspaket och startklarhet"}</h2><Why>Allt som beslutet bygger på sparas i en låst version. Ändringar i kostnad, tid, kvalitet eller effekt kräver en uttrycklig ny bedömning och ett nytt mänskligt beslut.</Why><form className="commitment-form" onSubmit={e=>{e.preventDefault();const a=assessments.find(x=>x.id===priority);if(!a||!actor)return;dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"SAVE_START_PREPARATION",targetId:token(),payload:{initiativeId:id,recipientBusinessIds:Object.values(state.entities.participations).filter(p=>p.initiativeId===id&&p.participantKind==="EFFECT_RECIPIENT"&&p.validFrom<=day&&(!p.validTo||p.validTo>=day)).flatMap(p=>p.businessId?[p.businessId]:[]),commitmentIds:selected,priorityAssessmentId:a.id,steeringProfileVersionId:a.steeringProfileVersionId,governanceVersionId:governance,fundingReference:form.fundingReference,capacityReference:form.capacityReference,legalReference:form.legalReference,qualityReference:form.qualityReference,prerequisitesReview:form.prerequisitesReview,economicRationale:form.economicRationale,costHorizon:{from:form.from,to:form.to}}});}}><div className="form-grid"><label>Prioriteringsunderlag<select required value={priority} onChange={e=>setPriority(e.target.value as PriorityAssessmentId)}><option value="">Välj underlagsversion</option>{assessments.map(a=><option key={a.id} value={a.id}>{a.totalScore} poäng · {a.status} · {a.assessedAt.slice(0,10)}</option>)}</select></label><label>Styrversion<select required value={governance} onChange={e=>setGovernance(e.target.value)}><option value="">Välj styrversion</option>{Object.values(state.entities.transformationGovernance).map(g=><option key={g.id} value={g.id}>Version {g.version} · {g.validFrom} · endast demo</option>)}</select></label>{Object.entries(labels).map(([key,label])=><Field key={key} label={label} value={form[key as keyof typeof form]} onChange={v=>setForm({...form,[key]:v})}/>)}<Field label="Ekonomisk jämförelse från" type="date" value={form.from} onChange={v=>setForm({...form,from:v})}/><Field label="Ekonomisk jämförelse till" type="date" value={form.to} onChange={v=>setForm({...form,to:v})}/><RoleSelect state={state} label="Beslutsfattare (demo)" kind="DECISION_MAKER" value={actor} onChange={setActor}/></div><fieldset><legend>Åtagandeversioner som ska ingå</legend>{!commitments.length&&<p>Inga lokala åtaganden finns ännu.</p>}{commitments.map(c=><label className="check" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(x=>x!==c.id))}/>{state.entities.businesses[c.recipientBusinessId].name} · {c.details?.metricName} · version {c.details?.version} · {acceptedCommitment(state,c.id)?"accepterat":"saknar accept"}</label>)}</fieldset><button>Spara nytt beslutspaket och pröva startklarhet</button></form>
    {priority&&actor&&<button className="secondary-action" onClick={()=>dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"REVIEW_PRIORITY_ASSESSMENT",targetId:priority,payload:{rationale:"Aktivt granskat i demonstrationen; är inte ett startbeslut."}})}>Bekräfta granskning av valt prioriteringsunderlag</button>}
    {preparation&&<section className="card"><h3>Senast sparade beslutspaket</h3><p>Bedöms vid demodatum {day}. Ändringar i formuläret ingår först när ett nytt paket sparats.</p><Blockers items={startBlockers(state,preparation,day)}/><div className="effect-metrics"><p>Verksamhetens planerade ekonomiska effekt<b>{format(preparedEconomics(state,preparation).plannedFinancialEffect)} SEK</b></p><p>Hela möjliggörandets kostnad<b>{format(preparedEconomics(state,preparation).cost)} SEK</b></p><p>Planerat netto i samma period<b>{format(preparedEconomics(state,preparation).plannedNet)} SEK</b></p></div><p>Planen är inte uppmätt effekt. Frigjord tid och kvalitet monetariseras inte. Negativt netto måste synliggöras och bedömas i beslutsmotiveringen.</p><form className="commitment-form" onSubmit={e=>{e.preventDefault();if(actor)dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"DECIDE_TRANSFORMATION",targetId:token(),payload:{preparationId:preparation.id,accepted,rationale,type:old?"CHANGE":"START",changeImpact:old?impacts:undefined}});}}><RoleSelect state={state} label="Person som fattar beslutet" kind="DECISION_MAKER" value={actor} onChange={setActor}/><Field label="Beslutsmotivering" value={rationale} onChange={setRationale}/>{old&&<div className="form-grid">{Object.entries({cost:"Kostnadskonsekvens",time:"Tidskonsekvens",quality:"Kvalitetskonsekvens",effect:"Effektkonsekvens"}).map(([key,label])=><Field key={key} label={label} value={impacts[key as keyof typeof impacts]} onChange={v=>setImpacts({...impacts,[key]:v})}/>)}</div>}<label className="check"><input required type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Jag fattar aktivt beslut inom mitt mandat och låser det sparade beslutspaketet.</label><button>{old?"Fatta ändringsbeslut":"Fatta startbeslut"}</button></form></section>}</>;
}

function MeasurementCard({state,dispatch,day,commitment:c}:WorkProps & {commitment:LocalEffectCommitment}) {
  const [actor,setActor]=useState<RoleAssignmentId|"">(""),[date,setDate]=useState(""),[evidence,setEvidence]=useState(""),[value,setValue]=useState(""),[quality,setQuality]=useState(""),[qualityMet,setQualityMet]=useState(""),[verify,setVerify]=useState(false);
  const d=c.details!,outcome=effectOutcome(state,c,day),points=Object.values(state.entities.measurementPoints).filter(m=>m.measurementPlanId===c.measurementPlanId);
  const meta=()=>({commandId:createId("Command",token()),actorRoleAssignmentId:actor as RoleAssignmentId,issuedAt:`${day}T12:00:00Z`});
  const latestForecast=Object.values(state.entities.effectForecasts).filter(f=>f.effectCommitmentId===c.id).sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))[0];
  return <article className="card"><span className="category">Beslutad version {d.version} · {state.entities.businesses[c.recipientBusinessId].name}</span><h3>{d.metricName}</h3><div className="effect-metrics"><p>Beslutad förbättring<b>{format(outcome.target)} {outcome.unit}</b></p><p>Senaste verifierade förbättring<b>{format(outcome.realized)} {outcome.realized===undefined?"":outcome.unit}</b></p><p>Kvalitetsgräns<b>{outcome.qualityMet===undefined?"Ej verifierad":outcome.qualityMet?"Uppfylld":"Inte uppfylld"}</b></p></div><p>Baseline {format(state.entities.baselines[c.baselineId].value)} · målnivå {format(c.targetValue)} · full effekt {d.fullEffectDate}</p>{latestForecast&&<p>Senaste prognos: nivå {format(latestForecast.forecastValue)} {c.unit} vid {latestForecast.forecastDate}. Prognosen är inte ett utfall.</p>}
    <RoleSelect state={state} label={`Aktiv person för ${d.metricName} (demo)`} value={actor} onChange={setActor}/>
    {!d.changeCompletedAt?<form className="edit-panel" onSubmit={e=>{e.preventDefault();if(actor)dispatch({...meta(),commandType:"CONFIRM_BUSINESS_CHANGE",targetId:c.id,payload:{date,evidence}});}}><h4>Bekräfta verksamhetsförändringen</h4><p>{d.changeDescription} · ansvarig {roleName(state,d.changeResponsibleId)} · senast {d.changeDueDate}</p><Field label="Förändringen genomförd" type="date" value={date} onChange={setDate}/><Field label="Evidens för att arbetssättet används" value={evidence} onChange={setEvidence}/><button>Bekräfta genomförd förändring</button></form>:<p className="gate ready">Verksamhetsförändringen bekräftad {d.changeCompletedAt} · {d.changeEvidence}</p>}
    <details><summary>Registrera en ny prognos</summary><form className="edit-panel" onSubmit={e=>{e.preventDefault();if(actor)dispatch({...meta(),commandType:"RECORD_EFFECT_FORECAST",targetId:token(),payload:{commitmentId:c.id,date,value:Number(value)}});}}><Field label="Prognosens måldatum" type="date" value={date} onChange={setDate}/><Field label="Prognostiserad nivå" type="number" value={value} onChange={setValue}/><button>Spara prognos</button></form></details>
    {d.changeCompletedAt&&<form className="commitment-form" onSubmit={e=>{e.preventDefault();if(actor)dispatch({...meta(),commandType:"RECORD_EFFECT_MEASUREMENT",targetId:token(),payload:{commitmentId:c.id,date,value:Number(value),evidence,qualityObservation:quality,qualityMet:qualityMet==="yes"}});}}><h4>Rapportera beslutad mätpunkt</h4><p>Mätningsansvarig: {roleName(state,state.entities.measurementPlans[c.measurementPlanId].responsibleRoleAssignmentId)}</p><div className="form-grid"><label>Beslutad mättidpunkt<select required value={date} onChange={e=>setDate(e.target.value)}><option value="">Välj datum</option>{d.measurementDates.map(x=><option key={x} value={x}>{x}</option>)}</select></label><Field label="Uppmätt nivå" type="number" value={value} onChange={setValue}/><Field label="Mätunderlag och evidens" value={evidence} onChange={setEvidence}/><Field label="Uppmätt kvalitet och underlag" value={quality} onChange={setQuality}/><label>Uppfylls beslutad kvalitetsgräns?<select required value={qualityMet} onChange={e=>setQualityMet(e.target.value)}><option value="">Välj bedömning</option><option value="yes">Ja</option><option value="no">Nej – avvikelse ska synas</option></select></label></div><button>Rapportera mätpunkt för verifiering</button></form>}
    {points.map(m=><div className="measurement-row" key={m.id}><b>{m.measuredAt}: {format(m.value)} {c.unit}</b><p>{m.evidenceReference} · {m.qualityObservation}</p>{m.verifiedAt?<p>Verifierat {m.verifiedAt.slice(0,10)} av {roleName(state,m.verifiedByRoleAssignmentId)}</p>:<><label className="check"><input type="checkbox" checked={verify} onChange={e=>setVerify(e.target.checked)}/>Jag har kontrollerat mätningen mot underlaget.</label><button onClick={()=>actor&&dispatch({...meta(),commandType:"VERIFY_EFFECT_MEASUREMENT",targetId:m.id,payload:{accepted:verify}})}>Verifiera mätpunkt som specialist</button></>}</div>)}
  </article>;
}

function CloseForm({state,dispatch,day,id}:WorkProps & {id:InitiativeId}) {
  const [actor,setActor]=useState<RoleAssignmentId|"">(""),[observation,setObservation]=useState(""),[evidence,setEvidence]=useState("");
  return state.entities.initiatives[id].closedAt?<div className="gate ready">Avslutat {state.entities.initiatives[id].closedAt?.slice(0,10)}. Låsta beslut och verifierade utfall bevaras.</div>:<details className="card"><summary>Avsluta och bevara lärandet</summary><form className="edit-panel" onSubmit={e=>{e.preventDefault();if(actor)dispatch({commandId:createId("Command",token()),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"COMPLETE_TRANSFORMATION",targetId:id,payload:{observation,evidence}});}}><p>Avslut kräver verifierade mätningar vid full effekt hos samtliga mottagare. Även utebliven eller negativ effekt ska bevaras.</p><RoleSelect state={state} label="Beslutsfattare vid avslut" kind="DECISION_MAKER" value={actor} onChange={setActor}/><Field label="Lärdom – vad fungerade och vad behöver ändras?" value={observation} onChange={setObservation}/><Field label="Underlag för lärdom och eventuell skalning" value={evidence} onChange={setEvidence}/><button>Avsluta med verifierat utfall</button></form></details>;
}
