import { useState } from "react";
import type { Command,CommandResult,DemoState } from "../application";
import { createId,type ChallengeId,type RoleAssignmentId } from "../domain";
import type { FlowStep } from "../application/selectors/flowSelectors";
import { roleName } from "./transformationHelpers";

export function FollowUpEditor({state,challengeId,step,day,dispatch}:{state:DemoState;challengeId:ChallengeId;step:FlowStep;day:string;dispatch:(command:Command)=>CommandResult}) {
 const challenge=state.entities.challenges[challengeId],initiativeId=challenge.relatedInitiativeIds[0];
 const block=step.key==="qualification"?"QUALIFICATION":step.key==="priority"?"PRIORITIZATION":step.key==="decision"?"START_DECISION":undefined;
 const requirement=block?Object.values(state.entities.completionRequirements).filter(r=>(r.challengeId===challengeId||(initiativeId&&r.initiativeId===initiativeId))&&r.blocks.includes(block)&&!["VERIFIED","NOT_APPLICABLE"].includes(r.status)).sort((a,b)=>(a.deadline??"9999").localeCompare(b.deadline??"9999"))[0]:undefined;
 const [open,setOpen]=useState(false);
 const followUp=challenge.stepFollowUps?.[step.key];
 const [responsible,setResponsible]=useState<RoleAssignmentId|"">(requirement?.responsibleRoleAssignmentId??followUp?.responsibleRoleAssignmentId??step.responsibleId??"");
 const [deadline,setDeadline]=useState(requirement?.deadline??followUp?.dueDate??step.dueDate??""),[verifier,setVerifier]=useState<RoleAssignmentId|"">(requirement?.verifierRoleAssignmentId??""),[message,setMessage]=useState("");
 const displayedRole=requirement?(requirement.status==="SUBMITTED"?requirement.verifierRoleAssignmentId:requirement.responsibleRoleAssignmentId):followUp?.responsibleRoleAssignmentId??step.responsibleId;
 const displayedDate=requirement?.deadline??followUp?.dueDate??step.dueDate;
 return <details className="follow-up-editor" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary><span>{displayedRole?roleName(state,displayedRole):"Utse ansvarig"}</span><span>{displayedDate??"Ange datum"} · ändra här</span></summary>{open&&<div><p><b>{requirement?`Komplettering: ${requirement.missingItem}`:`Nästa åtgärd i ${step.title}`}</b></p><p>{requirement?"Tilldelningen sparas direkt på detta kompletteringskrav.":"Utse vem som samordnar nästa åtgärd i steget och när den ska vara klar. Detta ändrar inte effektägare, beslutad mätplan eller andra formella ansvar."}</p><form onSubmit={e=>{e.preventDefault();if(!responsible||!deadline)return;const meta={commandId:createId("Command",`follow-up-${crypto.randomUUID()}`),actorRoleAssignmentId:challenge.initiatorRoleAssignmentId,issuedAt:`${day}T12:00:00Z`};const result=dispatch(requirement?{...meta,commandType:"ASSIGN_COMPLETION_RESPONSIBILITY",targetId:requirement.id,payload:{responsibleRoleAssignmentId:responsible,verifierRoleAssignmentId:verifier||undefined,deadline}}:{...meta,commandType:"UPDATE_STRATEGIC_CHALLENGE",targetId:challengeId,payload:{stepFollowUps:{...challenge.stepFollowUps,[step.key]:{responsibleRoleAssignmentId:responsible,dueDate:deadline}}}});setMessage(result.success?"Ansvar och datum sparade på rätt åtgärd.":result.errors.map(x=>x.description).join(" "));}}><label>{requirement?"Den som kompletterar":"Samordnare för nästa åtgärd"}<select required value={responsible} onChange={e=>setResponsible(e.target.value as RoleAssignmentId)}><option value="">Välj person och roll</option>{Object.values(state.entities.roleAssignments).map(r=><option key={r.id} value={r.id}>{roleName(state,r.id)}</option>)}</select></label><label>Klart senast<input required type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label>{requirement&&<label>Den som verifierar<select value={verifier} onChange={e=>setVerifier(e.target.value as RoleAssignmentId)}><option value="">Välj verifierare</option>{Object.values(state.entities.roleAssignments).map(r=><option key={r.id} value={r.id}>{roleName(state,r.id)}</option>)}</select></label>}<button>Spara ansvar och datum</button></form><p role="status">{message}</p></div>}</details>;
}
