import { useState } from "react";
import type { RoleAssignmentId } from "../domain";
import type { TransformationGovernance } from "../domain/transformation";
import { Field, RoleSelect, Why, type WorkProps } from "./transformationUi";
import { token } from "./transformationHelpers";

export function GovernanceWorkspace({state,dispatch,day}:WorkProps) {
  const versions=Object.values(state.entities.transformationGovernance).sort((a,b)=>b.version-a.version);
  const latest=versions[0];
  const [form,setForm]=useState({...latest}),[actor,setActor]=useState<RoleAssignmentId|"">(""),[feedback,setFeedback]=useState("");
  const labels:Partial<Record<keyof TransformationGovernance,string>>={decisionFunction:"Beslutsfunktion och mandatgränser",escalation:"Eskalering och politisk insyn",commitmentStatus:"Effektåtagandets formella status",changeRules:"Väsentlighetsgränser och ändringsbeslut",fundingPrinciple:"Finansiering och kostnadsfördelning",qualityCategories:"Effektkategorier, kvalitet och skyddsmått",methodOwner:"Ägare av gemensam metod och nomenklatur",governingDocuments:"Styrande dokument och gemensam mall",legalRequirements:"Lagkrav och obligatoriska bedömningar"};
  return <><section className="hero"><div><p className="eyebrow">GEMENSAM GRUND · TYDLIGA DEMONSTRATIONSANTAGANDEN</p><h1>Metod och styrning</h1><p className="lead">Ramarna ska vara gemensamma, synliga och versionsbundna. Organisationens beslut återstår.</p></div></section><p><a href="./inledning.html" target="_blank" rel="noreferrer">Separat inledande presentation</a> · <a href="./demoguide.html" target="_blank" rel="noreferrer">Körordning för demonstrationen</a></p><p className="demo-notice">Ej beslutad – används endast i demo.</p><Why>Demon visar hur framtida verksamhetsbeslut kan dokumenteras och följas. Textramar här är underlag för människor. De skapar inte automatiskt mandat eller nya maskinella regler. Startmandat och lokala effektägarmandat prövas separat. Prioriteringsvikter är körbar konfiguration i Prioritering.</Why><p>Uppladdning och tolkning av styrdokument, verkliga PPS-mallar och lagkrav är inte anslutna. Ange tills vidare gemensamma frågor och bedömningskrav nedan. En ifylld textruta är inte ett intyg om rättslig efterlevnad.</p><details className="point-detail"><summary>Dokumentera en ny styrversion</summary><form className="commitment-form" onSubmit={e=>{e.preventDefault();if(!actor)return;const {id:_id,version:_version,createdAt:_createdAt,demoAssumption:_demo,...payload}=form;void _id;void _version;void _createdAt;void _demo;const r=dispatch({commandId:token(),actorRoleAssignmentId:actor,issuedAt:`${day}T12:00:00Z`,commandType:"SAVE_TRANSFORMATION_GOVERNANCE",targetId:`GOVERNANCE-${token()}`,payload});setFeedback(r.success?"Ny styrversion sparad. Tidigare beslut behåller sin styrversion.":r.errors.map(x=>x.description).join(" "));}}><div className="form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea required value={String(form[key as keyof TransformationGovernance])} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<Field label="Gäller från" type="date" value={form.validFrom} onChange={validFrom=>setForm({...form,validFrom})}/><RoleSelect state={state} value={actor} onChange={setActor} kind="DECISION_MAKER" label="Person som versionssätter demostyrningen"/></div><button>Spara ny styrversion</button><p role="status">{feedback}</p></form></details><section className="section-block"><h2>Bevarade styrversioner</h2>{versions.map(g=><details className="card" key={g.id}><summary>Version {g.version} · gäller från {g.validFrom} · endast demo</summary><dl>{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(g[key as keyof TransformationGovernance])}</dd></div>)}</dl></details>)}</section></>;
}
