import { act, create, type ReactTestInstance } from "react-test-renderer";
import { expect, it } from "vitest";
import App from "../App";
import type { DemoState } from "../application";
import { initializeDemoState } from "../application/initializeDemoState";
import { caseFlow, type FlowStepKey } from "../application/selectors/flowSelectors";
import { latestDecision, effectOutcome } from "../application/selectors/transformationSelectors";
import { roleAssignments } from "../demo-data/peopleAndRoles";
import { referenceCommitment } from "../demo-data/referenceCommitment";

const text=(n:unknown):string=>typeof n==="string"?n:n&&typeof n==="object"&&"children" in n?(n as {children:unknown[]}).children.map(text).join(""):"";
it("leder ett nytt ärende från utkast genom faktisk prioriteringsgranskning till beslut, verifierad effekt och avslut",()=>{
 const root=create(<App demoState={initializeDemoState()}/>).root;
 const button=(label:string)=>{const b=root.findAllByType("button").find(b=>text(b).trim()===label);if(!b)throw Error(`Knapp saknas: ${label}`);return b;};
 const click=(label:string)=>act(()=>button(label).props.onClick());
 const control=(label:string,type:"input"|"select"|"textarea"="input")=>{const l=root.findAllByType("label").find(l=>text(l).startsWith(label));if(!l)throw Error(`Fält saknas: ${label}`);return l.findByType(type);};
 const enter=(label:string,value:string,type:"input"|"select"|"textarea"="input")=>act(()=>control(label,type).props.onChange({target:{value}}));
 const check=(label:string)=>act(()=>control(label).props.onChange({target:{checked:true}}));
 const submit=(label:string)=>{let f:ReactTestInstance|null=button(label);while(f&&f.type!=="form")f=f.parent;if(!f)throw Error(`Formulär saknas: ${label}`);act(()=>f!.props.onSubmit({preventDefault(){}}));};
 const state=()=>root.findAll(n=>typeof n.type==="function"&&n.props.state?.entities)[0].props.state as DemoState;
 const challenge=()=>Object.values(state().entities.challenges).find(c=>c.title==="Samordnad återkoppling – provärende")!;
 const id=()=>challenge().relatedInitiativeIds[0];
 const flow=()=>caseFlow(state(),challenge().id,"2026-09-06");
 const complete=(key:FlowStepKey)=>expect(flow().find(s=>s.key===key)?.status,key).toBe("COMPLETE");
 const next=(label:string)=>click(`Nästa steg: ${label} →`);
 const specialist=roleAssignments[1].id,decision=roleAssignments[2].id,initiator=roleAssignments[0].id;
 click("Ärenden");click("Registrera utmaning");
 enter("Titel","Samordnad återkoppling – provärende");enter("Problem","Besked hanteras flera gånger.","textarea");submit("Spara utkast i demosessionen");
 expect(root.findAllByProps({"data-step-work":"material"})).toHaveLength(1);
 enter("Nuläge","Manuell hantering tar onödig tid.","textarea");enter("Varför strategisk hantering?","Gemensam förbättring över verksamhetsgränser.","textarea");click("Registrera utmaning för fortsatt beredning");complete("material");
 for(const [label,value] of Object.entries({Syfte:"Kortare väntan och mindre dubbelarbete", "Önskat förändrat läge":"En gemensam rutin används",Avgränsning:"Återkoppling på servicefrågor",Alternativ:"Gemensam rutin jämfört med lokala förbättringar","Om vi avstår":"Dubbelarbete kvarstår"}))enter(label,value,"textarea");
 submit("Spara businesscase");click("Registrera initiativ för beredning");complete("businesscase");
 for(const [l,v] of Object.entries({Mätetal:"Årlig kostnad för dubbelarbete",Enhet:"SEK/år","Bedömda effektmottagare":"Verksamhet Inlopp","Låg potential":"100000","Förväntad potential":"180000","Hög potential":"220000","Evidens / underlagsreferens":"Tidsstudie och kalkyl","Antagande":"Volymen består","Effekthemtagningsfönster":"2027","Tidigast möjlig effekt":"2027-01-01","Full potential tidigast":"2027-12-31"}))enter(l,v);
 submit("Spara bedömd potential");complete("potential");next("Kvalificering");
 const configuration=Object.values(state().entities.qualificationConfigurations).find(c=>c.status==="ACTIVE")!;
 for(const c of configuration.criteria){
  const input=(label:string)=>root.findAllByType("input").find(i=>i.props["aria-label"]===label)!;
  act(()=>input(`Bedömning ${c.name}`).props.onChange({target:{value:"Bedömt för detta ärende"}}));
  act(()=>input(`Underlag ${c.name}`).props.onChange({target:{value:`Provunderlag: ${c.name}`}}));
  const card=()=>root.findAllByProps({className:"criterion"}).find(n=>text(n).includes(c.name))!;
  act(()=>card().findAllByType("button").find(b=>text(b)==="Spara punkt")!.props.onClick());
  if(c.requiresVerification)act(()=>card().findAllByType("button").find(b=>text(b)==="Specialistverifiera")!.props.onClick());
 }
 complete("qualification");next("Prioritering");
 const profile=Object.values(state().entities.steeringProfileVersions).find(p=>p.status==="ACTIVE")!;
 for(const c of profile.criteria){enter(`Poäng för ${c.name}`,"65");enter(`Underlag för ${c.name}`,"Bedömning i businesscase och kalkyl");}
 submit("Skapa prioriteringsunderlag från mina bedömningar");
 expect(flow().find(s=>s.key==="priority")?.status).not.toBe("COMPLETE");
 expect(button("Godkänn granskat prioriteringsunderlag").props.disabled).toBe(true);
 enter("Person som granskar prioriteringen",decision,"select");enter("Ställningstagande och motivering","Rimlig potential och förankrat underlag.","textarea");check("Jag har granskat underlaget");submit("Godkänn granskat prioriteringsunderlag");complete("priority");
 expect(latestDecision(state(),id())).toBeUndefined();next("Förutsättningar och körordning");
 enter("Ansvarig specialist för förutsättningsunderlaget",specialist,"select");enter("Leveransens namn","Gemensam återkopplingsrutin");enter("Vad ska finnas och varför?","Dokumenterad rutin och utbildning");enter("Planerad från","2026-09-06");enter("Ska finnas senast","2026-12-31");enter("Kriterium för att vara tillgänglig","Rutinen är beslutad och utbildningen genomförd");submit("Registrera planerad förutsättning");
 const node=Object.values(state().entities.executionNodes).find(n=>n.ownerInitiativeId===id())!;expect(node).toBeDefined();
 enter("Kostnaden tillhör",node.id,"select");enter("Kostnadsbelopp i SEK","120000");enter("Kostnadsperiod från","2026-09-06");enter("Kostnadsperiod till","2026-12-31");enter("Kalkylunderlag","Kalkyl över rutin, utbildning och införande");submit("Registrera kostnadsunderlag");complete("conditions");next("Lokala effektåtaganden");
 enter("Ny mottagande verksamhet",referenceCommitment.businessId,"select");enter("Person som registrerar deltagandet",specialist,"select");submit("Lägg till effektmottagare");
 enter("Effektmottagande verksamhet",referenceCommitment.businessId,"select");
 const vals={Mätetal:"Årlig kostnad för dubbelarbete","Omfattning –":"Återkoppling inom verksamhet Inlopp",Enhet:"SEK/år","Beslutat målvärde":"420000","Planerad ekonomisk effekt per kalenderår":"2027:180000","Lokalt utgångsvärde":"600000","Baseline uppmätt":"2026-06-30","Baselineunderlag":"Granskad tidsstudie","Datakälla och uttag":"Ekonomi och samma urval vid mätning","Mättidpunkter –":"2027-12-31","Bedömning av full effekt":"2027-12-31","Effektfönster från":"2027-01-01","Effektfönster till":"2027-12-31","Nödvändig verksamhetsförändring":"Inför och använd gemensam återkopplingsrutin","Förändringen ska vara genomförd":"2026-12-31","Bekräftad mottagarkapacitet":"Två utbildningsdagar och ansvarig samordnare","Kvalitets- eller skyddsmått":"Andel besvarade frågor","Godtagbar kvalitetsgräns":"Minst 95 procent"};
 for(const [l,v] of Object.entries(vals))enter(l,v);
 enter("Mätningsansvarig",initiator,"select");enter("Ansvarig för verksamhetsförändringen",initiator,"select");enter("Lokal effektägare med mandat",referenceCommitment.details.ownerRoleAssignmentId,"select");enter("Person som dokumenterar utkastet",specialist,"select");check("Baseline är kontrollerad");submit("Spara åtagandeutkast");
 expect(flow().find(s=>s.key==="commitments")?.status).not.toBe("COMPLETE");
 enter("Jag agerar som effektägare",referenceCommitment.details.ownerRoleAssignmentId,"select");enter("Mandat att binda","Lokalt mandat för verksamhetsförändringen");check("Jag accepterar aktivt");submit("Acceptera lokalt effektåtagande");complete("commitments");next("Startbeslut");
 click("Hämta befintliga åtaganden och styrunderlag");
 for(const l of ["Finansiering –","Genomförandekapacitet –","Lagkrav och","Kvalitetskrav –","Beroenden –","Samlad ekonomi –"])enter(l,"Granskat underlag för detta provärende.");
 enter("Ekonomisk jämförelse till","2027-12-31");enter("Beslutsfattare (demo)",decision,"select");submit("Spara nytt beslutspaket och pröva startklarhet");
 expect(button("Fatta startbeslut").props.disabled).toBe(false);
 expect(latestDecision(state(),id())).toBeUndefined();enter("Beslutsmotivering","Genomför enligt granskat och accepterat underlag");check("Jag fattar aktivt beslut");submit("Fatta startbeslut");complete("decision");
 const frozen=JSON.stringify(latestDecision(state(),id()));next("Genomförande och förändring");
 enter("Demodatum","2026-12-31");click("Tillämpa demodatum");enter("Aktiv person för",initiator,"select");enter("Förändringen genomförd","2026-12-31");enter("Evidens för att arbetssättet","Rutinen används enligt verksamhetens uppföljning");submit("Bekräfta genomförd förändring");
 complete("implementation");next("Effektuppföljning");enter("Aktiv person för",initiator,"select");
 enter("Demodatum","2027-12-31");click("Tillämpa demodatum");enter("Beslutad mättidpunkt","2027-12-31","select");enter("Uppmätt nivå","450000");enter("Mätunderlag och evidens","Verifierbart ekonomiskt utfall");enter("Uppmätt kvalitet och underlag","98 procent besvarade frågor");enter("Uppfylls beslutad kvalitetsgräns?","yes","select");submit("Rapportera mätpunkt för verifiering");
 const commitment=()=>Object.values(state().entities.effectCommitments).find(c=>c.initiativeId===id())!;
 expect(effectOutcome(state(),commitment(),"2027-12-31").realized).toBeUndefined();
 enter("Aktiv person för",specialist,"select");check("Jag har kontrollerat mätningen");click("Verifiera mätpunkt som specialist");
 expect(effectOutcome(state(),commitment(),"2027-12-31").realized).toBe(150000);
 expect(JSON.stringify(latestDecision(state(),id()))).toBe(frozen);
 next("Avslut, lärande och skalning");
 enter("Beslutsfattare vid avslut",decision,"select");enter("Lärdom –","150000 uppnått av 180000 planerat. Förbättra rutinen inför skalning.");enter("Underlag för lärdom","Verifierat utfall och verksamhetsanalys");submit("Avsluta med verifierat utfall");
 expect(state().entities.initiatives[id()].closedAt).toBeDefined();
 expect(text(root)).toContain("Målet nåddes inte");
 expect(text(root)).toContain("150000 uppnått av 180000 planerat. Förbättra rutinen inför skalning.");
 click("Kontrollrum");click("Effektuppföljning");expect(text(root)).toContain("Samordnad återkoppling – provärende");
});
