import { useState } from "react";
import type { DemoState } from "../application";
import type { InitiativeId,ExecutionNodeId } from "../domain";
import { portfolioLens,simulatedPotential } from "../application/selectors/portfolioLensSelectors";
import { capacityStatus } from "../application/selectors/capacitySelectors";
import { costSummary,costsByOrigin } from "../application/selectors/costSelectors";
import { activeCommitments,latestDecision } from "../application/selectors/transformationSelectors";
import { roleName,format } from "./transformationHelpers";

const stamp=(date:string)=>Date.parse(`${date.slice(0,10)}T00:00:00Z`);
const nodeStatus={AVAILABLE:"Tillgänglig",PLANNED:"Planerad",BLOCKED:"Blockerad",UNKNOWN:"Ej bedömd"};
export function PortfolioLens({state,area,day,from,to,mode,open,openNode}:{state:DemoState;area:string;day:string;from:string;to:string;mode:"plan"|"simulation";open:(id:InitiativeId)=>void;openNode:(id:InitiativeId,nodeId:ExecutionNodeId)=>void}) {
  const lens=portfolioLens(state,area,day);
  const [group,setGroup]=useState("time");
  const selectedIds=lens.selected.map(i=>i.id);
  const capacities=capacityStatus(state).filter(c=>selectedIds.includes(c.demand.initiativeId)&&c.demand.period.from<=to&&c.demand.period.to>=from);
  const costs=costSummary(state,selectedIds,"ESTIMATE",{from,to});
  if(!from||!to||from>to)return <p role="alert">Välj ett giltigt tidsfönster med från-datum före till-datum.</p>;
  if(!lens.selected.length)return <p>Inga initiativ har deltagande verksamheter i detta område vid lägesdatumet. Välj ett annat område.</p>;
  if(mode==="simulation")return <EffectSimulation key={area} state={state} ids={selectedIds} from={from} to={to}/>;
  const start=stamp(from),end=stamp(to)+86400000,span=end-start;
  const plotWidth=800,rowHeight=46;
  const nodes=lens.nodes.filter(n=>n.plannedPeriod.from<=to&&n.plannedPeriod.to>=from);
  const position=new Map(nodes.map((n,i)=>[n.id,i]));
  const x=(date:string)=>Math.max(0,Math.min(plotWidth,(stamp(date)-start)/span*plotWidth));
  const missingOutside=lens.nodes.length-nodes.length;
  return <section className="portfolio-lens" aria-label="Portföljens tid och beroenden">
    <header className="lens-heading"><div><h1>Vad behöver ske först?</h1><p>{lens.selected.length} initiativ i urvalet · {lens.externalIds.size} möjliggörande initiativ utanför urvalet.</p></div><label>Visa efter<select value={group} onChange={e=>setGroup(e.target.value)}><option value="time">Tid och beroenden</option><option value="shared">Gemensamma beroenden</option><option value="capacity">Kapacitet och pengar</option></select></label></header>
    <p className="lens-date">Planfönster {from}–{to} · lägesdatum {day}. En planerad period betyder inte att arbetet har startat.</p>
    {group==="time"&&<>
      <p className="lens-legend"><span>I valt område</span><span className="external">Utanför urvalet · behövs som förutsättning</span> Linjer visar registrerade beroenden; streckat betyder rådgivande.</p>
      <div className="timeline-scroll"><div className="timeline-chart" style={{minWidth:1120}}>
        <div className="timeline-labels"><div className="timeline-axis-label">Leverans / förutsättning</div>{nodes.map(n=><div key={n.id} style={{height:rowHeight}} className={n.ownerInitiativeId&&lens.externalIds.has(n.ownerInitiativeId)?"external":""}><button className="text-button" onClick={()=>{const id=n.ownerInitiativeId??n.contextInitiativeIds[0];if(id)openNode(id,n.id);}} title={n.title}>{n.title}</button><small>{nodeStatus[n.availabilityStatus]}{n.ownerInitiativeId&&lens.externalIds.has(n.ownerInitiativeId)?" · utanför urvalet":""}</small></div>)}</div>
        <svg width={plotWidth} height={Math.max(100,nodes.length*rowHeight+36)} role="img" aria-label={`Planerade leveranser och beroenden ${from} till ${to}. Textalternativ finns under diagrammet.`}>
          <defs><marker id="dependency-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="#64798b"/></marker></defs>
          {Array.from({length:5},(_,i)=>{const date=new Date(start+span*i/4).toISOString().slice(0,10);return <g key={i}><line x1={i*plotWidth/4} x2={i*plotWidth/4} y1={30} y2={nodes.length*rowHeight+32} stroke="#dce6e1"/><text x={i*plotWidth/4} y={19} textAnchor={i===0?"start":i===4?"end":"middle"} fontSize="13" fill="#4d6258">{date}</text></g>;})}
          {nodes.map((n,i)=>{const outside=!!n.ownerInitiativeId&&lens.externalIds.has(n.ownerInitiativeId);return <g key={n.id}><rect x={x(n.plannedPeriod.from)} y={i*rowHeight+39} width={Math.max(3,x(n.plannedPeriod.to)-x(n.plannedPeriod.from))} height={18} rx={4} fill={outside?"#506fa8":"#21785e"} opacity={n.availabilityStatus==="AVAILABLE"?1:.55}/><title>{n.title}: {n.plannedPeriod.from}–{n.plannedPeriod.to}, {nodeStatus[n.availabilityStatus]}</title></g>;})}
          {lens.dependencies.filter(d=>position.has(d.predecessorNodeId)&&position.has(d.successorNodeId)).map(d=>{const a=state.entities.executionNodes[d.predecessorNodeId],b=state.entities.executionNodes[d.successorNodeId],ax=x(a.plannedPeriod.to),bx=x(b.plannedPeriod.from),ay=position.get(a.id)!*rowHeight+48,by=position.get(b.id)!*rowHeight+48;return <path key={d.id} d={`M${ax} ${ay} C${ax+14} ${ay},${bx-14} ${by},${bx} ${by}`} stroke="#64798b" fill="none" strokeWidth={1.5} strokeDasharray={d.blocking?undefined:"4 3"} markerEnd="url(#dependency-arrow)"/>;})}
          {day>=from&&day<=to&&<g><line x1={x(day)} x2={x(day)} y1={28} y2={nodes.length*rowHeight+32} stroke="#b64b31" strokeWidth={2}/><title>Lägesdatum {day}</title></g>}
        </svg>
      </div></div>
      {missingOutside>0&&<p>{missingOutside} förutsättningar ligger utanför planfönstret. De finns kvar i beroendelistan nedan.</p>}
      <details className="lens-detail"><summary>Alla beroenden med ansvar och datum · {lens.dependencies.length}</summary>{lens.dependencies.map(d=>{const a=state.entities.executionNodes[d.predecessorNodeId],b=state.entities.executionNodes[d.successorNodeId];return <article key={d.id}><strong>{a.title} → {b.title}</strong><p>{d.rationale}</p><p>{d.blocking?(d.requiredAt==="NODE_START"?"Krav före start":"Krav vid senare milstolpe"):"Rådgivande"} · {nodeStatus[a.availabilityStatus]} · behövs {a.neededAt} · {roleName(state,a.responsibleRoleAssignmentId)}</p>{a.plannedPeriod.to>b.plannedPeriod.from&&d.blocking&&d.requiredAt==="NODE_START"&&<p className="progress-alert">Planeringskonflikt: förutsättningens planerade slut ligger efter efterföljarens start.</p>}</article>;})}</details>
      <h2>Initiativens läge</h2><div className="lens-initiatives">{lens.selected.map(i=>{const cs=activeCommitments(state,i.id),started=latestDecision(state,i.id);return <article key={i.id}><button className="text-button" onClick={()=>open(i.id)}>{i.title} →</button><p>{i.closedAt?`Avslutat ${i.closedAt.slice(0,10)}`:!started?"Inte startat":cs.length&&cs.every(c=>c.details?.changeCompletedAt)?"Verksamhetsförändringar bekräftade · följs för effekt":"Genomförande pågår"}</p><small>{cs.length?`Effektfönster: ${cs.map(c=>`${c.details?.effectWindow.from}–${c.details?.effectWindow.to}`).join(", ")}`:"Inget beslutat effektfönster ännu"}</small></article>;})}</div>
    </>}
    {group==="shared"&&<><p>Grupperat efter samma registrerade förutsättning, även indirekta beroenden. Antalet visar berörda initiativ; det är inte ett löfte om startklarhet.</p>{!lens.shared.length&&<p>Inga gemensamma beroenden finns registrerade för urvalet.</p>}{lens.shared.map(({node,consumers})=><article className="shared-dependency" key={node.id}><div><h2>{node.title}</h2><p>{nodeStatus[node.availabilityStatus]} · behövs {node.neededAt} · {roleName(state,node.responsibleRoleAssignmentId)}</p><b>{consumers.length} initiativ är beroende av denna förutsättning</b></div><ul>{consumers.map(id=><li key={id}><button className="text-button" onClick={()=>open(id)}>{state.entities.initiatives[id].title} →</button></li>)}</ul></article>)}</>}
    {group==="capacity"&&<><div className="lens-economic"><h2>Pengar, tid och kompetens</h2><p><strong>{costs.sourceRefs.length?`${format(costs.amount)} SEK`:"Kostnadsunderlag saknas"}</strong> · bedömd kostnad för {from}–{to}{costs.completeness==="INCOMPLETE"?" · ofullständig delsumma":""}.</p><p>Delade kostnadsposter räknas en gång inom urvalet. Hela kostnaden för en gemensam förutsättning kan ingå; områdesvyer ska inte summeras.</p></div>
      {!capacities.length&&<p>Inga kvantifierade resursbehov finns registrerade i perioden. Det betyder inte att kapacitet är säkrad.</p>}
      <p>Visar behov som berör planfönstret. Kapacitetsläget prövas över varje behovs hela angivna period, även konkurrerande behov från andra områden.</p><div className="table-scroll"><table><thead><tr><th>Initiativ och kompetens</th><th>Period</th><th>Eget behov</th><th>Samtidigt behov / tillgång</th><th>Läge</th></tr></thead><tbody>{capacities.map(c=><tr key={c.demand.id}><td><button className="text-button" onClick={()=>open(c.demand.initiativeId)}>{state.entities.initiatives[c.demand.initiativeId].title}</button><br/>{state.entities.capabilities[c.demand.capabilityId]?.name} · {c.demand.poolReference}</td><td>{c.demand.period.from}–{c.demand.period.to}</td><td>{format(c.demand.amount)} {c.demand.unit}</td><td>{format(c.requested)} / {c.status==="UNKNOWN"?"okänd":format(c.available)} {c.demand.unit}</td><td>{c.status==="AVAILABLE"?"Ryms i registrerad kapacitet":c.status==="CONFLICT"?`Konflikt · saknar ${format(c.shortage)} ${c.demand.unit}`:"Tillgång behöver verifieras"}{c.competingDemandIds.length>0&&<details><summary>Delad resurs · {c.competingDemandIds.length} andra behov</summary>{c.competingDemandIds.map(id=>{const demand=state.entities.capacityDemands[id as keyof typeof state.entities.capacityDemands];return demand?<p key={id}>{state.entities.initiatives[demand.initiativeId]?.title} · {demand.period.from}–{demand.period.to}</p>:null;})}</details>}</td></tr>)}</tbody></table></div>
    </>}
  </section>;
}

function EffectSimulation({state,ids,from,to}:{state:DemoState;ids:InitiativeId[];from:string;to:string}) {
  const [id,setId]=useState(ids[0]),[factors,setFactors]=useState<Record<string,number>>({}),[delay,setDelay]=useState(0),[costFactor,setCostFactor]=useState(100);
  const rows=simulatedPotential(state,id,factors,delay),cost=costSummary(state,[id],"ESTIMATE",{from,to});
  const costPosts=costsByOrigin(state,[id]).filter(c=>c.economicStatus==="ESTIMATE"&&c.period.from<=to&&c.period.to>=from);
  return <section className="portfolio-lens" aria-label="Simulera effekt och kostnad"><header><h1>Pröva vad som gör skillnad</h1><p className="simulation-notice">Scenario · ändrar varken grunddata, prioriteringsunderlag, beslut eller verifierad effekt.</p></header><div className="simulation-controls"><label>Initiativ<select value={id} onChange={e=>{setId(e.target.value as InitiativeId);setFactors({});setDelay(0);setCostFactor(100);}}>{ids.map(id=><option key={id} value={id}>{state.entities.initiatives[id].title}</option>)}</select></label><label>Förskjut effektens datum<input type="range" min={0} max={36} step={1} value={delay} onChange={e=>setDelay(Number(e.target.value))}/>{delay} månader</label><label>Pröva kostnadsnivå<input type="range" min={50} max={200} step={5} value={costFactor} onChange={e=>setCostFactor(Number(e.target.value))}/>{costFactor}% av bedömningen</label><button className="secondary-action" onClick={()=>{setFactors({});setDelay(0);setCostFactor(100);}}>Återställ scenario</button></div>
    <div className="simulation-effects">{!rows.length&&<p>Effektpotential saknas. Ta fram den i steg 2 innan du simulerar.</p>}{rows.map(r=><article key={r.source.id}><h2>{r.source.effectMeasureCode}</h2><p>{r.source.recipientBusinessId?state.entities.businesses[r.source.recipientBusinessId]?.name:r.source.recipientScenario??"Omfattning behöver anges"} · {r.source.category==="MONEY"?"Pengar":r.source.category==="RELEASED_TIME"?"Frigjord tid":"Kvalitet / verksamhetseffekt"}</p><label>Effektnivå · {factors[r.source.id]??100}%<input aria-label={`Effektnivå ${r.source.effectMeasureCode}`} type="range" min={0} max={150} step={5} value={factors[r.source.id]??100} onChange={e=>setFactors({...factors,[r.source.id]:Number(e.target.value)})}/></label><p className="simulated-value">{format(r.expected)} {r.source.unit}<small> Grundbedömning {format(r.source.expectedValue)} · scenariointervall {format(r.lower)}–{format(r.upper)}</small></p><p>Första möjliga effekt {r.firstEffect} · full effekt {r.fullEffect}</p><details><summary>Vad bygger effekten på?</summary><ul>{r.source.assumptions.map(a=><li key={a}>{a}</li>)}</ul><p>Tidsfönster i underlaget: {r.source.realizationWindow}. Osäkerhet: {r.source.uncertainty}. Bedömt {r.source.assessedAt.slice(0,10)}.</p><p>Reglaget skalar den registrerade bedömningen proportionellt. Det är ingen prognosmodell eller ny evidensbedömning.</p></details></article>)}</div>
    <div className="lens-economic"><h2>Kostnad i scenariot</h2><p>{costPosts.length?`${format(cost.amount*costFactor/100)} SEK · grundbedömning ${format(cost.amount)} SEK`:"Kostnadsunderlag saknas i perioden"} · {from}–{to}{cost.completeness==="INCOMPLETE"?" · ofullständig delsumma":""}.</p><p>Datumförskjutningen gäller möjlig effekt. Den flyttar inte resursbokningar eller kostnadsperioder. Frigjord tid monetariseras inte automatiskt och olika effekttyper summeras inte.</p><details><summary>Visa kostnadsdelarna · {costPosts.length} poster</summary>{costPosts.map(c=><p key={c.id}>{state.entities.executionNodes[c.executionNodeId]?.title??c.originReference} · {format(c.amount)} {c.currency} · {c.period.from}–{c.period.to}</p>)}</details></div>
  </section>;
}
