import type { DemoState } from '../application';
import type { InitiativeId } from '../domain';
import { currentEffectPotentials } from '../application/selectors/effectPotentialSelectors';
import { acceptedCommitment, activeCommitments, effectOutcome, latestDecision } from '../application/selectors/transformationSelectors';
import type { FlowStepKey } from '../application/selectors/flowSelectors';
import { format, roleName } from './transformationHelpers';

export function PortfolioEffects({state,ids,area,day,open}:{state:DemoState;ids:InitiativeId[];area:string;day:string;open:(id:InitiativeId,section?:FlowStepKey)=>void}) {
 const inArea=(businessId?:string)=>area==='Alla'||!!businessId&&Object.values(state.entities.businesses).find(b=>b.id===businessId)?.businessAreaId===area;
 const potentials=ids.filter(id=>!latestDecision(state,id)).flatMap(id=>currentEffectPotentials(state,id)).filter(p=>inArea(p.recipientBusinessId));
 const commitments=ids.flatMap(id=>{
   if(latestDecision(state,id))return activeCommitments(state,id);
   const preparation=Object.values(state.entities.startPreparations).filter(p=>p.initiativeId===id).at(-1);
   return (preparation?.commitmentIds??[]).flatMap(key=>{const c=state.entities.effectCommitments[key];return c&&acceptedCommitment(state,c.id)?[c]:[];});
 }).filter(c=>inArea(c.recipientBusinessId));
 const verified=commitments.filter(c=>!!latestDecision(state,c.initiativeId)&&effectOutcome(state,c,day).realized!==undefined);
 const receiver=(id?:string)=>id?Object.values(state.entities.businesses).find(b=>b.id===id)?.name??'Mottagare saknas':'Gemensamt scenario · mottagare framgår av underlaget';
 return <section aria-label="Effekter i valt urval" className="portfolio-effects"><h2>Från möjlig effekt till verifierat resultat</h2><p>Gäller initiativen i ditt urval. Faserna är olika perspektiv på effekter och ska aldrig adderas. Antalen nedan avser underlag och åtaganden, inte antal ärenden.</p><div className="opportunity-cards">
 <article className="opportunity mint"><h3>Bedömd potential</h3><b className="opportunity-value">{potentials.length}<small> aktuella bedömningar före start</small></b><p>Möjlig effekt. Icke bindande och före avdrag för kostnader.</p><details><summary>Visa potential, mottagare och tidsfönster</summary>{!potentials.length?<p>Inga bedömningar före start i urvalet.</p>:potentials.map(p=><div className="effect-source" key={p.id}><button className="text-button" onClick={()=>open(p.initiativeId,'potential')}>{state.entities.initiatives[p.initiativeId].title} →</button><p>{receiver(p.recipientBusinessId)}</p><b>{format(p.expectedValue)} {p.unit}</b><p>{p.effectMeasureCode.replaceAll('_',' ').toLocaleLowerCase('sv')} · intervall {format(p.lowerBound)}–{format(p.upperBound)} {p.unit}</p><small>{p.realizationWindow} · full potential {p.fullPotentialDate}</small></div>)}</details></article>
 <article className="opportunity blue"><h3>Beslutad effekthemtagning</h3><b className="opportunity-value">{commitments.length}<small> lokala effektåtaganden</small></b><p>Aktivt accepterade åtaganden i beslutspaket eller låst beslut. Ett åtagande före start är inte ett startbeslut.</p><details><summary>Visa mål, effektägare och mätplan</summary>{!commitments.length?<p>Inga accepterade åtaganden i beslutspaket i urvalet.</p>:commitments.map(c=><div className="effect-source" key={c.id}><button className="text-button" onClick={()=>open(c.initiativeId,'commitments')}>{state.entities.initiatives[c.initiativeId].title} →</button><p>{receiver(c.recipientBusinessId)} · {latestDecision(state,c.initiativeId)?'Låst i start- eller ändringsbeslut':'Accepterat före start'}</p><b>{format(effectOutcome(state,c,day).target)} {c.unit} beslutad förbättring</b><p>{c.details?.metricName}</p><small>{c.details?.effectWindow.from}–{c.details?.effectWindow.to} · full effekt {c.details?.fullEffectDate}</small><p>{c.details&&roleName(state,c.details.ownerRoleAssignmentId)}</p></div>)}</details></article>
 <article className="opportunity lilac"><h3>Verifierad effekt</h3><b className="opportunity-value">{verified.length}<small> åtaganden med verifierat utfall</small></b><p>Senaste verifierade mätning per åtagande vid {day}. Ej uppmätt betyder inte noll.</p><details><summary>Visa uppmätta resultat och underlag</summary>{!verified.length?<p>Inga verifierade utfall i urvalet ännu.</p>:verified.map(c=>{const outcome=effectOutcome(state,c,day);return <div className="effect-source" key={c.id}><button className="text-button" onClick={()=>open(c.initiativeId,'measurement')}>{state.entities.initiatives[c.initiativeId].title} →</button><p>{receiver(c.recipientBusinessId)}</p><b>{format(outcome.realized)} {outcome.unit} verifierad förbättring</b><p>{c.details?.metricName}{outcome.qualityMet===false?' · Kvalitetsavvikelse':''}</p><small>{c.details?.effectWindow.from}–{c.details?.effectWindow.to} · jämfört med lokal baseline</small></div>})}</details></article>
 </div><p className="chart-caption">Underlagen hålls separata när mottagare, scenarier, mått eller tidsfönster skiljer sig. Årstakt är inte ackumulerad besparing. Ekonomisk periodplan, kostnader och jämförbara utfall finns under Effektuppföljning.</p></section>;
}
