import { useState, useRef, useEffect } from "react";
import { createId, type ExecutionNodeId, type InitiativeId, type RoleAssignmentId } from "../domain";
import { Field, RoleSelect, Why, type WorkProps } from "./transformationUi";
import { token } from "./transformationHelpers";
import { prerequisiteGraph } from "../application/selectors/executionSelectors";

export function PrerequisiteEditor({state,dispatch,day,id,focus,initialNodeId}:WorkProps & {id:InitiativeId;focus?:"cost"|"availability";initialNodeId?:ExecutionNodeId}) {
  const [actor,setActor]=useState<RoleAssignmentId|"">(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[owner,setOwner]=useState(id),[kind,setKind]=useState("ENABLING_DELIVERY"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[criteria,setCriteria]=useState(""),[pre,setPre]=useState<ExecutionNodeId|"">(initialNodeId??""),[post,setPost]=useState<ExecutionNodeId|"">(""),[rationale,setRationale]=useState(""),[evidence,setEvidence]=useState(""),[amount,setAmount]=useState(""),[recurrence,setRecurrence]=useState("ONE_TIME"),[category,setCategory]=useState("COMMON_INVESTMENT");
  const editorRef=useRef<HTMLDetailsElement>(null);
  useEffect(()=>{if(focus)editorRef.current?.scrollIntoView?.({block:"start"});},[focus]);
  const nodes=Object.values(state.entities.executionNodes),graph=prerequisiteGraph(state,id);
  const meta=()=>({commandId:createId("Command",token()),actorRoleAssignmentId:actor as RoleAssignmentId,issuedAt:`${day}T12:00:00Z`});
  const nodeSelect=(label:string,value:string,onChange:(v:ExecutionNodeId)=>void)=><label>{label}<select required value={value} onChange={e=>onChange(e.target.value as ExecutionNodeId)}><option value="">Välj leverans eller förmåga</option>{nodes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label>;
  return <details ref={editorRef} className="card" open={focus?true:undefined}><summary>Bygg på ärendet med förutsättningar, beroenden och kostnader</summary><Why>Återanvänd en befintlig förutsättning genom att länka till den. Dess ägare och kostnadspost behålls. Relationen anger varför nästa steg behöver vänta. Planerade underlag efter start ändrar inte den låsta beslutsbaslinjen; de måste tas med i ett nytt ändringsbeslut.</Why><RoleSelect state={state} label="Ansvarig specialist för förutsättningsunderlaget" value={actor} onChange={setActor} kind="SPECIALIST"/>
    <details><summary>1. Lägg till en leverans eller förändring</summary><form className="commitment-form" onSubmit={e=>{e.preventDefault();if(actor)dispatch({...meta(),commandType:"CREATE_EXECUTION_NODE",targetId:createId("ExecutionNode",token()),payload:{ownerInitiativeId:owner,contextInitiativeIds:[id],title,description,nodeKind:kind as "ENABLING_DELIVERY",responsibleRoleAssignmentId:actor,plannedPeriod:{from,to},neededAt:to,availabilityCriteria:criteria,availabilityStatus:"PLANNED",availabilityEvidenceRefs:[]}});}}><div className="form-grid"><Field label="Leveransens namn" value={title} onChange={setTitle}/><Field label="Vad ska finnas och varför?" value={description} onChange={setDescription}/><label>Ägande initiativ<select value={owner} onChange={e=>setOwner(e.target.value as InitiativeId)}>{Object.values(state.entities.initiatives).map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select></label><label>Typ<select value={kind} onChange={e=>setKind(e.target.value)}><option value="ENABLING_DELIVERY">Möjliggörande leverans</option><option value="BUSINESS_CHANGE">Verksamhetsförändring</option><option value="LOCAL_ADOPTION">Lokalt införande</option><option value="FOLLOW_UP_PREPARATION">Förberedelse för mätning</option></select></label><Field label="Planerad från" type="date" value={from} onChange={setFrom}/><Field label="Ska finnas senast" type="date" value={to} onChange={setTo}/><Field label="Kriterium för att vara tillgänglig" value={criteria} onChange={setCriteria}/></div><button>Registrera planerad förutsättning</button></form></details>
    <details><summary>2. Ange vad som måste komma först</summary><form className="commitment-form" onSubmit={e=>{e.preventDefault();if(actor&&pre&&post)dispatch({...meta(),commandType:"ADD_DEPENDENCY",targetId:createId("Dependency",token()),payload:{predecessorNodeId:pre,successorNodeId:post,dependencyType:"FINISH_TO_START",requiredDeliverable:criteria,blocking:true,requiredAt:"NODE_START",rationale,sourceRefs:[evidence]}});}}><div className="form-grid">{nodeSelect("Förutsättning som måste vara klar",pre,setPre)}{nodeSelect("Leverans som måste vänta",post,setPost)}<Field label="Vilken leverans krävs?" value={criteria} onChange={setCriteria}/><Field label="Varför blockerar beroendet?" value={rationale} onChange={setRationale}/><Field label="Underlag för beroendet" value={evidence} onChange={setEvidence}/></div><button>Koppla blockerande beroende</button></form></details>
    <details open={focus==="cost"?true:undefined}><summary>3. Kostnad för en förutsättning</summary><form className="commitment-form" onSubmit={e=>{e.preventDefault();const n=nodes.find(n=>n.id===pre);if(actor&&n?.ownerInitiativeId)dispatch({...meta(),commandType:"REGISTER_COST_ENTRY",targetId:createId("CostEntry",token()),payload:{initiativeId:n.ownerInitiativeId,executionNodeId:n.id,originReference:`SYNTHETIC-${token()}`,category:category as "COMMON_INVESTMENT",period:{from,to},amount:Number(amount),currency:"SEK",economicStatus:"ESTIMATE",recurrence:recurrence as "ONE_TIME",sourceRefs:[evidence],assessmentVersion:1}});}}><div className="form-grid">{nodeSelect("Kostnaden tillhör",pre,setPre)}<label>Kostnadsslag<select value={category} onChange={e=>setCategory(e.target.value)}><option value="COMMON_INVESTMENT">Gemensam investering</option><option value="LOCAL_CONNECTION">Lokal anslutning</option><option value="DATA_INFORMATION">Tvätt och förberedelse av data</option><option value="BUSINESS_CHANGE">Verksamhetsförändring</option><option value="TRAINING">Utbildning</option><option value="OPERATIONS">Drift</option></select></label><Field label="Kostnadsbelopp i SEK" type="number" value={amount} onChange={setAmount}/><label>Återkommande?<select value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="ONE_TIME">Engångskostnad i angiven period</option><option value="RECURRING_ANNUAL">Årsbelopp under angiven period</option></select></label><Field label="Kostnadsperiod från" type="date" value={from} onChange={setFrom}/><Field label="Kostnadsperiod till" type="date" value={to} onChange={setTo}/><Field label="Kalkylunderlag" value={evidence} onChange={setEvidence}/></div><p>Ny kostnadspost. Återanvändning av en befintlig leverans kräver ingen ny kopia av dess kostnad.</p><button>Registrera kostnadsunderlag</button></form></details>
    <details open={focus==="availability"?true:undefined}><summary>4. Verifiera en tillgänglig förutsättning</summary><form className="commitment-form" onSubmit={e=>{e.preventDefault();if(actor&&pre)dispatch({...meta(),commandType:"RECORD_NODE_AVAILABILITY",targetId:pre,payload:{availabilityStatus:"AVAILABLE",availabilityEvidenceRefs:[evidence],availabilityVerifiedAt:`${day}T12:00:00Z`}});}}><div className="form-grid"><label>Förutsättning i detta ärende<select required value={pre} onChange={e=>setPre(e.target.value as ExecutionNodeId)}><option value="">Välj förutsättning</option>{graph.nodes.map(n=><option key={n.id} value={n.id}>{n.title} · {n.availabilityStatus}</option>)}</select></label><Field label="Underlag som visar att tillgänglighetskriteriet är uppfyllt" value={evidence} onChange={setEvidence}/></div><p>Detta registrerar tillgänglighet. Det registrerar aldrig verksamhetseffekt.</p><button>Verifiera tillgänglig förutsättning</button></form></details>
  </details>;
}
